
package janitha;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Update_Employee extends javax.swing.JFrame {

  
  PreparedStatement pst =null;
  ResultSet rs=null;
  DBconnect dbc = new DBconnect();
    public Update_Employee() {
        //setUndecorated(true);
        initComponents();
        
        try {
             new Thread(new Runnable() {

            @Override
            public void run() {
                Date d = new Date();
                SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

                String s2 = sd.format(d);
                date1.setText(s2);

            }
        }).start();
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    Date d = new Date();
                    String s = d.toString();
                    String ar[] = s.split(" ");
                    time1.setText(ar[3]);

                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
         
    }
    String id;
    String type;
    String title;
    String name;
    String iname;
    String day;
    String month;
    String year; 
    String nic;
    String padd;
    String poadd;
    String tell;
    String mob;
    String email;
    String bank;
    String acc_no;
    String etf;
    String epf;
    String r_day;
    String r_month;
    String r_year;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emptxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        typebox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        titlebox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        nibox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        daybox = new javax.swing.JComboBox<>();
        monthbox = new javax.swing.JComboBox<>();
        yearbox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        nicbox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addbox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        poaddbox = new javax.swing.JTextField();
        telbox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mobbox = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emailbox = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        bankbox = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        accbox = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        etfbox = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        epfbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rday = new javax.swing.JComboBox<>();
        rmonth = new javax.swing.JComboBox<>();
        ryear = new javax.swing.JComboBox<>();
        cmb_search = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        dlt_btn = new javax.swing.JButton();
        upd_btn = new javax.swing.JButton();
        backbtn = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 660));
        jPanel1.setLayout(null);

        jPanel2.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel2.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Employee ID\n");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(16, 184, 70, 16);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Update / Delete Details");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 20, 210, 30);
        jPanel2.add(emptxt);
        emptxt.setBounds(129, 177, 130, 28);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Type");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 225, 100, 16);

        typebox.setBackground(new java.awt.Color(102, 204, 0));
        typebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type...", "Permanent", "Contract Basis" }));
        jPanel2.add(typebox);
        typebox.setBounds(123, 222, 130, 20);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Title");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 269, 90, 14);

        titlebox.setBackground(new java.awt.Color(102, 204, 0));
        titlebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Title...", "Manager", "Accountant", "Sales Rep", "Driver", "Labor" }));
        jPanel2.add(titlebox);
        titlebox.setBounds(123, 265, 130, 20);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Full Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 313, 90, 16);
        jPanel2.add(namebox);
        namebox.setBounds(123, 305, 255, 30);
        jPanel2.add(nibox);
        nibox.setBounds(124, 360, 256, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name with Initials");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 368, 110, 16);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date of Birth");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(16, 411, 90, 16);

        daybox.setBackground(new java.awt.Color(102, 204, 0));
        daybox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(daybox);
        daybox.setBounds(125, 408, 60, 20);

        monthbox.setBackground(new java.awt.Color(102, 204, 0));
        monthbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPanel2.add(monthbox);
        monthbox.setBounds(191, 408, 90, 20);

        yearbox.setBackground(new java.awt.Color(102, 204, 0));
        yearbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", " ", " ", " " }));
        jPanel2.add(yearbox);
        yearbox.setBounds(287, 408, 93, 20);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NIC.No");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(16, 536, 80, 16);
        jPanel2.add(nicbox);
        nicbox.setBounds(130, 528, 179, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Permanent Address");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(418, 173, 110, 16);
        jPanel2.add(addbox);
        addbox.setBounds(532, 154, 240, 52);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Postal Address");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(418, 253, 100, 16);
        jPanel2.add(poaddbox);
        poaddbox.setBounds(532, 234, 240, 53);
        jPanel2.add(telbox);
        telbox.setBounds(532, 300, 190, 30);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tel No");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(421, 306, 77, 20);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mobile No");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(421, 351, 90, 16);

        mobbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobboxActionPerformed(evt);
            }
        });
        jPanel2.add(mobbox);
        mobbox.setBounds(532, 343, 190, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Email");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(421, 400, 80, 16);
        jPanel2.add(emailbox);
        emailbox.setBounds(532, 392, 190, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Bank");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(421, 448, 90, 16);
        jPanel2.add(bankbox);
        bankbox.setBounds(532, 440, 190, 30);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Account Number");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(790, 212, 100, 16);

        accbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accboxActionPerformed(evt);
            }
        });
        jPanel2.add(accbox);
        accbox.setBounds(928, 204, 130, 30);

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("E.T.F Number");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(790, 253, 90, 16);

        etfbox.setPreferredSize(new java.awt.Dimension(130, 20));
        etfbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etfboxActionPerformed(evt);
            }
        });
        jPanel2.add(etfbox);
        etfbox.setBounds(928, 252, 130, 30);

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("E.P.F Number");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(796, 308, 114, 16);
        jPanel2.add(epfbox);
        epfbox.setBounds(928, 300, 130, 30);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registered Date");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(16, 449, 100, 16);

        rday.setBackground(new java.awt.Color(102, 204, 0));
        rday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(rday);
        rday.setBounds(126, 446, 59, 20);

        rmonth.setBackground(new java.awt.Color(102, 204, 0));
        rmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPanel2.add(rmonth);
        rmonth.setBounds(191, 446, 90, 20);

        ryear.setBackground(new java.awt.Color(102, 204, 0));
        ryear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2016", "2015", "2014", "2013", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", " " }));
        ryear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ryearActionPerformed(evt);
            }
        });
        jPanel2.add(ryear);
        ryear.setBounds(287, 446, 93, 20);

        cmb_search.setForeground(new java.awt.Color(51, 204, 0));
        cmb_search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One...", "ID", "Name" }));
        jPanel2.add(cmb_search);
        cmb_search.setBounds(951, 85, 107, 20);

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Search With :");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(867, 88, 80, 16);

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        jPanel2.add(txt_search);
        txt_search.setBounds(868, 111, 190, 30);

        search_btn.setBackground(new java.awt.Color(51, 204, 0));
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        jPanel2.add(search_btn);
        search_btn.setBounds(978, 147, 80, 23);

        table.setBackground(new java.awt.Color(0, 255, 0));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp ID", "Name", "Title ", "ETF Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 593, 1060, 112);

        dlt_btn.setBackground(new java.awt.Color(51, 204, 0));
        dlt_btn.setText("Delete");
        dlt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlt_btnActionPerformed(evt);
            }
        });
        jPanel2.add(dlt_btn);
        dlt_btn.setBounds(979, 493, 80, 23);

        upd_btn.setBackground(new java.awt.Color(51, 204, 0));
        upd_btn.setText("Update");
        upd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_btnActionPerformed(evt);
            }
        });
        jPanel2.add(upd_btn);
        upd_btn.setBounds(881, 493, 80, 23);

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backbtn.png"))); // NOI18N
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        jPanel2.add(backbtn);
        backbtn.setBounds(990, 10, 25, 25);

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/logoutbtn.png"))); // NOI18N
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
        });
        jPanel2.add(logoutbtn);
        logoutbtn.setBounds(1020, 10, 25, 25);

        time1.setBackground(new java.awt.Color(255, 255, 255));
        time1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        time1.setForeground(new java.awt.Color(255, 255, 255));
        time1.setText("time");
        jPanel2.add(time1);
        time1.setBounds(750, 0, 70, 20);

        date1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("date");
        jPanel2.add(date1);
        date1.setBounds(750, 20, 60, 10);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/closebtn.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel21);
        jLabel21.setBounds(1050, 10, 25, 25);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/minimizebtn.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel22);
        jLabel22.setBounds(960, 10, 25, 25);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/main2.jpg"))); // NOI18N
        jPanel2.add(jLabel20);
        jLabel20.setBounds(0, 0, 1100, 720);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1080, 810);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 800));

        setSize(new java.awt.Dimension(1095, 758));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mobboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobboxActionPerformed

    private void accboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accboxActionPerformed

    private void ryearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ryearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ryearActionPerformed

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked
        
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
                Reg_Employee reg = new Reg_Employee();
                reg.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_backbtnMouseClicked

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        try{
            String search = txt_search.getText();
            if (cmb_search.getSelectedItem().toString()== "ID"){
                String sql ="select * from employee where eid = '"+search+"'";
                //JOptionPane.showConfirmDialog(null,"stae");
                pst=dbc.con.prepareStatement(sql);
                rs=pst.executeQuery();
                while(rs.next()){
                String id = rs.getString("eid");
                String name = rs.getString("name_i");
                String title = rs.getString("title");
                String etf = rs.getString("etf");
        
                
                model.addRow(new Object[]{id,name,title,etf});
                }
                
                
                
                
            
        }
            
            else if(cmb_search.getSelectedItem().toString()== "Name"){
            
            
            
                String sql ="select * from employee where name_i LIKE '%"+search+"%'";
                //JOptionPane.showConfirmDialog(null,"stae");
                pst=dbc.con.prepareStatement(sql);
                rs=pst.executeQuery();
                while(rs.next()){
                String id = rs.getString("eid");
                String name = rs.getString("name_i");
                String title = rs.getString("title");
                String etf = rs.getString("etf");
        
                
                model.addRow(new Object[]{id,name,title,etf});
                }
            
            
            
            
            
            }
            
            
            
            
        
            
        }
         catch (Exception e){
         
         
        }
        
    }//GEN-LAST:event_search_btnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
         DefaultTableModel model = (DefaultTableModel) table.getModel();
         int row = table.getSelectedRow();
         
         String id = model.getValueAt(row, 0).toString();
         
         try {
         
          String sql = "select * from employee where eid = '"+id+"'";
          pst=dbc.con.prepareStatement(sql);
                rs=pst.executeQuery(); 
                while(rs.next()){
                emptxt.setText(rs.getString("eid"));
                typebox.setSelectedItem(rs.getString("e_type")); 
                titlebox.setSelectedItem(rs.getString("title")); 
                namebox.setText(rs.getString("f_name"));
                nibox.setText(rs.getString("name_i"));
                daybox.setSelectedItem(rs.getString("day")); 
                monthbox.setSelectedItem(rs.getString("month")); 
                yearbox.setSelectedItem(rs.getString("year")); 
                nicbox.setText(rs.getString("nic"));
                addbox.setText(rs.getString("p_add"));
                poaddbox.setText(rs.getString("po_add"));
                telbox.setText(rs.getString("tel"));
                mobbox.setText(rs.getString("mobile"));
                emailbox.setText(rs.getString("email"));
                bankbox.setText(rs.getString("bank"));
                accbox.setText(rs.getString("acc_num"));
                etfbox.setText(rs.getString("etf"));
                epfbox.setText(rs.getString("epf"));
                rday.setSelectedItem(rs.getString("r_day")); 
                rmonth.setSelectedItem(rs.getString("r_month")); 
                ryear.setSelectedItem(rs.getString("r_year")); 
                
                
                
                
                
                }
                
                
         
         
         
         
         }
         
         catch(Exception e){}
        
        
        
    }//GEN-LAST:event_tableMouseClicked

    private void upd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_btnActionPerformed
        int mes = JOptionPane.showConfirmDialog(null, "Do you really wan to Update");
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        if(mes ==0){
            
        String id1=emptxt.getText();
        String type = typebox.getSelectedItem().toString();
        title = titlebox.getSelectedItem().toString();
        name = namebox.getText();
        iname = nibox.getText();
        day = daybox.getSelectedItem().toString();
        month = monthbox.getSelectedItem().toString();
        year = yearbox.getSelectedItem().toString();
        nic = nicbox.getText();
        padd = addbox.getText();
        poadd = poaddbox.getText();
        tell = telbox.getText();
        mob = mobbox.getText();
        email = emailbox.getText();
        bank = bankbox.getText();
        acc_no = accbox.getText();
        etf = etfbox.getText();
        epf = epfbox.getText();
        r_day = rday.getSelectedItem().toString();
        r_month = rmonth.getSelectedItem().toString();
        r_year = ryear.getSelectedItem().toString();
        try{
        String sql1="UPDATE employee SET eid ='"+id1+"',e_type='"+type+"',title='"+title+"',f_name='"+name+"',name_i='"+iname+"',day='"+day+"',month='"+ month+"',year='"+year+"',nic='"+nic+"',p_add='"+padd+"',po_add='"+poadd+"',tel='"+tell+"',mobile='"+mob+"',email='"+email+"',bank='"+bank+"',acc_num='"+acc_no+"',etf='"+etf+"',epf='"+epf+"',r_day='"+r_day+"',r_month='"+r_month+"',r_year='"+r_year+"'";
         pst=dbc.con.prepareStatement(sql1);
         //JOptionPane.showConfirmDialog(null, "stat");
        
         pst.executeUpdate();
       JOptionPane.showMessageDialog(null, "Update Successfully");
        
        
        
        }
        catch(Exception e){
         JOptionPane.showMessageDialog(null,e);}
        
        }
        
         model.addRow(new Object[]{emptxt.getText(),nibox.getText(),titlebox.getSelectedItem().toString(),etfbox.getText()});
       
        
    }//GEN-LAST:event_upd_btnActionPerformed
    
    private void dlt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlt_btnActionPerformed
        
        int mes = JOptionPane.showConfirmDialog(null, "Do you really want to Delete");
        if(mes ==0){
            
        id=emptxt.getText();
        type = typebox.getSelectedItem().toString();
        title = titlebox.getSelectedItem().toString();
        name = namebox.getText();
        iname = nibox.getText();
        day = daybox.getSelectedItem().toString();
        month = monthbox.getSelectedItem().toString();
        year = yearbox.getSelectedItem().toString();
        nic = nicbox.getText();
        padd = addbox.getText();
        poadd = poaddbox.getText();
        tell = telbox.getText();
        mob = mobbox.getText();
        email = emailbox.getText();
        bank = bankbox.getText();
        acc_no = accbox.getText();
        etf = etfbox.getText();
        epf = epfbox.getText();
        r_day = rday.getSelectedItem().toString();
        r_month = rmonth.getSelectedItem().toString();
        r_year = ryear.getSelectedItem().toString();
        try{
        String sql1="DELETE from employee where eid ='"+id+"'";
         pst=dbc.con.prepareStatement(sql1);
         //JOptionPane.showConfirmDialog(null, "stat");
        
         pst.executeUpdate();
       JOptionPane.showMessageDialog(null, "Deleted Successfully");
       emptxt.setText("");
        
        
        
        }
        catch(Exception e){
         JOptionPane.showConfirmDialog(null, e);}
        
        }
        
        
    }//GEN-LAST:event_dlt_btnActionPerformed

    private void etfboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etfboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etfboxActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accbox;
    private javax.swing.JTextField addbox;
    private javax.swing.JLabel backbtn;
    private javax.swing.JTextField bankbox;
    private javax.swing.JComboBox<String> cmb_search;
    private javax.swing.JLabel date1;
    private javax.swing.JComboBox<String> daybox;
    private javax.swing.JButton dlt_btn;
    private javax.swing.JTextField emailbox;
    private javax.swing.JTextField emptxt;
    private javax.swing.JTextField epfbox;
    private javax.swing.JTextField etfbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoutbtn;
    private javax.swing.JTextField mobbox;
    private javax.swing.JComboBox<String> monthbox;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField nibox;
    private javax.swing.JTextField nicbox;
    private javax.swing.JTextField poaddbox;
    private javax.swing.JComboBox<String> rday;
    private javax.swing.JComboBox<String> rmonth;
    private javax.swing.JComboBox<String> ryear;
    private javax.swing.JButton search_btn;
    private javax.swing.JTable table;
    private javax.swing.JTextField telbox;
    private javax.swing.JLabel time1;
    private javax.swing.JComboBox<String> titlebox;
    private javax.swing.JTextField txt_search;
    private javax.swing.JComboBox<String> typebox;
    private javax.swing.JButton upd_btn;
    private javax.swing.JComboBox<String> yearbox;
    // End of variables declaration//GEN-END:variables
}
