package visura;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pramodi Weerasooriya
 */
public class Inventry extends javax.swing.JFrame {

    Connection con = null;          // Setting db connect to null
    PreparedStatement pst = null;                       // setting sql query statement to null
    ResultSet rs = null;
    
    public Inventry() {
        initComponents();
        con =Db.connect();
        
       try {
             new Thread(new Runnable() {

            @Override
            public void run() {
                Date d = new Date();
                SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

                String s2 = sd.format(d);
                date1.setText(s2);

            }
        }).start();
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    Date d = new Date();
                    String s = d.toString();
                    String ar[] = s.split(" ");
                    time1.setText(ar[3]);

                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
        
    }
    
     public void tableLoad()
    {
        try {
             String sql = "SELECT * FROM inventry";  
            pst=con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            invnt_tbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
      public void tableLoad(String a)
    {
        try {
             String sql1 = a;  
            pst=con.prepareStatement(sql1);
            rs = pst.executeQuery();
            
            
            
            invnt_tbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
    
    private String code;
    private String size;
    private String category;
    private String qty;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Add = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Qty_txt = new javax.swing.JTextField();
        Qty = new javax.swing.JLabel();
        btl_size = new javax.swing.JComboBox<>();
        Btl_cat = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        invnt_tbl = new javax.swing.JTable();
        srch = new javax.swing.JButton();
        srch_txt = new javax.swing.JTextField();
        srch_qty = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ctgry_lbl = new javax.swing.JLabel();
        size_lbl = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        lgout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setPreferredSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(null);

        Add.setBackground(new java.awt.Color(0, 153, 0));
        Add.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add);
        Add.setBounds(210, 430, 120, 30);

        Clear.setBackground(new java.awt.Color(0, 153, 0));
        Clear.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear);
        Clear.setBounds(720, 430, 120, 30);

        Qty_txt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jPanel1.add(Qty_txt);
        Qty_txt.setBounds(240, 300, 170, 30);

        Qty.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Qty.setForeground(new java.awt.Color(255, 255, 255));
        Qty.setText("Quantity");
        jPanel1.add(Qty);
        Qty.setBounds(120, 300, 100, 30);

        btl_size.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btl_size.setForeground(new java.awt.Color(255, 255, 255));
        btl_size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bottle Size", "200ml", "250ml", "350ml", "400ml", "500ml PET", "1.5L PET" }));
        jPanel1.add(btl_size);
        btl_size.setBounds(240, 200, 170, 30);

        Btl_cat.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Btl_cat.setForeground(new java.awt.Color(255, 255, 255));
        Btl_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bottle Category", "Apple Soda", "Orange Barly", "Cream Soda", "EGB", "EGB Lite", "Lemonade", "Necto", "Orange Crush", "Soda", "Tonic", "Twistee Peach", "Twistee Apple", "Bitter Lemon", "Ginger Ale", "Wild Elephant" }));
        jPanel1.add(Btl_cat);
        Btl_cat.setBounds(240, 100, 170, 30);

        invnt_tbl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        invnt_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item Code", "Category", "Size", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        invnt_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invnt_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(invnt_tbl);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 510, 870, 140);

        srch.setBackground(new java.awt.Color(0, 153, 0));
        srch.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        srch.setForeground(new java.awt.Color(255, 255, 255));
        srch.setText("Search");
        srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchActionPerformed(evt);
            }
        });
        jPanel1.add(srch);
        srch.setBounds(610, 190, 130, 30);

        srch_txt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jPanel1.add(srch_txt);
        srch_txt.setBounds(610, 120, 170, 30);

        srch_qty.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        srch_qty.setForeground(new java.awt.Color(255, 255, 255));
        srch_qty.setText("Item Number");
        jPanel1.add(srch_qty);
        srch_qty.setBounds(480, 120, 100, 30);

        update_btn.setBackground(new java.awt.Color(0, 153, 0));
        update_btn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        update_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn);
        update_btn.setBounds(460, 430, 120, 30);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(460, 82, 440, 210);

        ctgry_lbl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        ctgry_lbl.setForeground(new java.awt.Color(255, 255, 255));
        ctgry_lbl.setText("Bottle Category");
        jPanel1.add(ctgry_lbl);
        ctgry_lbl.setBounds(120, 100, 100, 30);

        size_lbl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        size_lbl.setForeground(new java.awt.Color(255, 255, 255));
        size_lbl.setText("Bottle Size");
        jPanel1.add(size_lbl);
        size_lbl.setBounds(120, 200, 100, 30);

        time1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        time1.setForeground(new java.awt.Color(255, 255, 255));
        time1.setText("time");
        jPanel1.add(time1);
        time1.setBounds(705, 0, 70, 16);

        date1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("date");
        jPanel1.add(date1);
        date1.setBounds(705, 15, 90, 20);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backbtn.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(930, 10, 25, 25);

        lgout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/logoutbtn.png"))); // NOI18N
        jPanel1.add(lgout);
        lgout.setBounds(960, 10, 25, 25);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventory Control");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 20, 300, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/closebtn.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(990, 10, 25, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/minimizebtn.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(900, 10, 25, 25);

        bg.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        bg.setForeground(new java.awt.Color(255, 255, 255));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backsup.jpg"))); // NOI18N
        bg.setMaximumSize(new java.awt.Dimension(1024, 720));
        bg.setMinimumSize(new java.awt.Dimension(1024, 720));
        bg.setPreferredSize(new java.awt.Dimension(1024, 720));
        jPanel1.add(bg);
        bg.setBounds(0, 0, 1024, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) invnt_tbl.getModel();
        
        model.setRowCount(0);
        
         btl_size.setSelectedItem("Bottle Size");
         Btl_cat.setSelectedItem("Bottle Caregory");
         Qty_txt.setText("0");
         //srch_txt.setText(" ");
    }//GEN-LAST:event_ClearActionPerformed

    private void srchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchActionPerformed
        // TODO add your handling code here:
        
        //model = (DefaultTableModel)inventry.getModel();
        //model.setRowCount(0);
        code = srch_txt.getText();
        
        //JOptionPane.showConfirmDialog(null, "1");
        
        String sql = "SELECT * from inventry where code LIKE '"+code+"'";
        try {
              pst =con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        //JOptionPane.showConfirmDialog(null, "2");
        
        invnt_tbl.setModel(DbUtils.resultSetToTableModel(rs));
        
        tableLoad("a");
        } 
        catch (Exception e) {
        }
        
        String txt = srch_txt.getText();
    }//GEN-LAST:event_srchActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
       
        //JOptionPane.showMessageDialog(null, "ok");
        //code = (String) btl_size.getSelectedItem();
        category = (String) Btl_cat.getSelectedItem();
        size = (String) btl_size.getSelectedItem();
        qty = Qty_txt.getText();
        
        try {
            String sql = "INSERT INTO `inventry`(size,category,qty) VALUES ('"+category+"','"+size+"','"+qty+"')";
            pst = con.prepareStatement(sql);
            pst.execute();
            tableLoad();
            
        } 
        catch (Exception e) {
            System.out.println(e);
        }
  
    }//GEN-LAST:event_AddActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do You Really Want to Update");
         
         if(x==0)
         {
             
             category = Btl_cat.getSelectedItem().toString();
             size = btl_size.getSelectedItem().toString();          
             qty = Qty_txt.getText();
             
             //JOptionPane.showMessageDialog(null, "ok");
             
             String sql = "UPDATE inventry SET code='"+code+"',category='"+category+"',size='"+size+"',  qty= '"+qty+"' where code='"+code+"'";
             //JOptionPane.showMessageDialog(null, "ok");
             try {
                 pst =con.prepareStatement(sql);
                 pst.execute();
                 
                 tableLoad();
                 
                // JOptionPane.showMessageDialog(null, "ok");
                 
            btl_size.setSelectedItem("Bottle Size");     
            Btl_cat.setSelectedItem("Bottle Category");
            Qty_txt.setText("");
            
                 JOptionPane.showMessageDialog(null, "ok");
             } catch (Exception e) {
                System.out.println(e); 
             }
         }
    }//GEN-LAST:event_update_btnActionPerformed

    private void invnt_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invnt_tblMouseClicked
        // TODO add your handling code here:
        
        int r= invnt_tbl.getSelectedRow();
        
        size = invnt_tbl.getValueAt(r, 1).toString();
        category = invnt_tbl.getValueAt(r, 2).toString();  
       qty =invnt_tbl.getValueAt(r,3).toString();
       
        btl_size.setSelectedItem(size);
        Btl_cat.setSelectedItem(category);
        Qty_txt.setText(qty);
        

    }//GEN-LAST:event_invnt_tblMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
         main ma = new main();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JComboBox<String> Btl_cat;
    private javax.swing.JButton Clear;
    private javax.swing.JLabel Qty;
    private javax.swing.JTextField Qty_txt;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bg;
    private javax.swing.JComboBox<String> btl_size;
    private javax.swing.JLabel ctgry_lbl;
    private javax.swing.JLabel date1;
    private javax.swing.JTable invnt_tbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lgout;
    private javax.swing.JLabel size_lbl;
    private javax.swing.JButton srch;
    private javax.swing.JLabel srch_qty;
    private javax.swing.JTextField srch_txt;
    private javax.swing.JLabel time1;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
