package visura;


import gehan.Home;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pramodi Weerasooriya
 */
public class main extends javax.swing.JFrame {

    Connection con = null;          // Setting db connect to null
    PreparedStatement pst = null;                       // setting sql query statement to null
    ResultSet rs = null; 
    
    public main() {
        initComponents();
         con = Db.connect();
          try {
             new Thread(new Runnable() {

            @Override
            public void run() {
                Date d = new Date();
                SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

                String s2 = sd.format(d);
                date1.setText(s2);

            }
        }).start();
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    Date d = new Date();
                    String s = d.toString();
                    String ar[] = s.split(" ");
                    time1.setText(ar[3]);

                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        cat_lbl = new javax.swing.JLabel();
        size_lbl = new javax.swing.JLabel();
        qty_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setPreferredSize(new java.awt.Dimension(1024, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/inventory.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(380, 270, 80, 80);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/purchasing.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(600, 270, 80, 90);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 0));
        jLabel9.setText("Purchasing Order");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(590, 380, 102, 17);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 0));
        jLabel10.setText("Inventory");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(390, 380, 59, 17);

        time1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        time1.setForeground(new java.awt.Color(255, 255, 255));
        time1.setText("time");
        jPanel1.add(time1);
        time1.setBounds(720, 0, 80, 20);

        date1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("date");
        jPanel1.add(date1);
        date1.setBounds(720, 15, 90, 20);

        cat_lbl.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cat_lbl.setForeground(new java.awt.Color(255, 255, 255));
        cat_lbl.setText("Bottle Category");
        cat_lbl.setMinimumSize(new java.awt.Dimension(100, 30));
        cat_lbl.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(cat_lbl);
        cat_lbl.setBounds(380, 480, 100, 30);

        size_lbl.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        size_lbl.setForeground(new java.awt.Color(255, 0, 0));
        size_lbl.setText("Bottle Size");
        size_lbl.setMinimumSize(new java.awt.Dimension(100, 30));
        size_lbl.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(size_lbl);
        size_lbl.setBounds(520, 480, 100, 30);

        qty_lbl.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        qty_lbl.setForeground(new java.awt.Color(255, 255, 255));
        qty_lbl.setText("Quantity");
        qty_lbl.setMinimumSize(new java.awt.Dimension(100, 30));
        qty_lbl.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(qty_lbl);
        qty_lbl.setBounds(660, 480, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backbtn.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(930, 10, 25, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/logoutbtn.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(960, 10, 25, 25);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inventory Control and Purchasing");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 24, 410, 60);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Notification");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 450, 150, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/minimizebtn.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(900, 10, 25, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/closebtn.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(990, 10, 25, 25);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backmain.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(0, 0, 1024, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        new Thread(new Runnable() {
            
            public void run() {
                String category = null;
        String size = null;
        String qty = null;
        
        String sql = "SELECT category,size,qty FROM `inventry` where qty < 100 ";
        
        try
            {    
                pst  = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                
                while(rs.next())
                {
                    category = rs.getString("category");
                    size = rs.getString("size");
                    qty = rs.getString("qty");

                   cat_lbl.setText(String.valueOf(category));  
                   size_lbl.setText(String.valueOf(size));
                   qty_lbl.setText(String.valueOf(qty));
                }
                  
                
                  
            }
            catch(SQLException e)
            {
                  JOptionPane.showMessageDialog(null,"error : cannot execute sql  ");       
            }
                
            }
        }).start();
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Inventry in = new Inventry();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        purchasing ps = new purchasing();
        ps.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel cat_lbl;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel qty_lbl;
    private javax.swing.JLabel size_lbl;
    private javax.swing.JLabel time1;
    // End of variables declaration//GEN-END:variables
}
