package visura;

import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class purchasing extends javax.swing.JFrame {

    Connection con = null;          // Setting db connect to null
    PreparedStatement pst = null;                       // setting sql query statement to null
    ResultSet rs = null;
    
    public purchasing() {
        initComponents();
        con =Db.connect();
        
         try {
             new Thread(new Runnable() {

            @Override
            public void run() {
                java.util.Date d = new java.util.Date();
                SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

                String s2 = sd.format(d);
                date1.setText(s2);

            }
        }).start();
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    java.util.Date d = new java.util.Date();
                    String s = d.toString();
                    String ar[] = s.split(" ");
                    time1.setText(ar[3]);

                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        } 
        
    }    
     public void tableLoad()
    {
        try {
             String sql = "SELECT * FROM purchasing";  
            pst=con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            purch_tbl1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }
     
//     public void tableLoad(String a)
//    {
//        try {
//             String sql1 = a;  
//            pst=con.prepareStatement(sql1);
//            rs = pst.executeQuery();
//      
//            purch_tbl1.setModel(DbUtils.resultSetToTableModel(rs));
//        } catch (Exception e) {
//        }
//    }
    
    private String code;
    private String size;
    private String category;
    private String qty;
    private String invoiceNo;
    private String date;
    private String price;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        purch_tbl1 = new javax.swing.JTable();
        Add1 = new javax.swing.JButton();
        Clear1 = new javax.swing.JButton();
        btl_size1 = new javax.swing.JComboBox<String>();
        Btl_cat1 = new javax.swing.JComboBox<String>();
        Qty1 = new javax.swing.JLabel();
        invoice = new javax.swing.JLabel();
        invoice_txt = new javax.swing.JTextField();
        stck = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        backLbl = new javax.swing.JLabel();
        lgOutLbl = new javax.swing.JLabel();
        BtlSizeLbl = new javax.swing.JLabel();
        btlCatLbl = new javax.swing.JLabel();
        StckDateChooser = new com.toedter.calendar.JDateChooser();
        Qty_txt1 = new javax.swing.JTextField();
        priceLbl = new javax.swing.JLabel();
        price_Txt = new javax.swing.JTextField();
        discount_lbl = new javax.swing.JLabel();
        totVal_lbl = new javax.swing.JLabel();
        totVal_txt = new javax.swing.JTextField();
        discount_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setPreferredSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(null);

        purch_tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Item Id", "Invoice No", "Stock Date", "Delivered Quantity", "Unit Price", "Discount", "Total Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        purch_tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purch_tbl1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                purch_tbl1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(purch_tbl1);
        if (purch_tbl1.getColumnModel().getColumnCount() > 0) {
            purch_tbl1.getColumnModel().getColumn(3).setMinWidth(110);
            purch_tbl1.getColumnModel().getColumn(3).setMaxWidth(140);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 520, 860, 150);

        Add1.setBackground(new java.awt.Color(0, 153, 0));
        Add1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Add1.setForeground(new java.awt.Color(255, 255, 255));
        Add1.setText("Add");
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });
        jPanel1.add(Add1);
        Add1.setBounds(330, 480, 120, 30);

        Clear1.setBackground(new java.awt.Color(0, 153, 0));
        Clear1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Clear1.setForeground(new java.awt.Color(255, 255, 255));
        Clear1.setText("Clear");
        Clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear1ActionPerformed(evt);
            }
        });
        jPanel1.add(Clear1);
        Clear1.setBounds(520, 480, 120, 30);

        btl_size1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btl_size1.setForeground(new java.awt.Color(255, 255, 255));
        btl_size1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bottle Size", "200ml", "250ml", "350ml", "400ml", "500ml PET", "1.5L PET" }));
        btl_size1.setMinimumSize(new java.awt.Dimension(140, 30));
        btl_size1.setPreferredSize(new java.awt.Dimension(140, 30));
        jPanel1.add(btl_size1);
        btl_size1.setBounds(260, 120, 170, 30);

        Btl_cat1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Btl_cat1.setForeground(new java.awt.Color(255, 255, 255));
        Btl_cat1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bottle Category", "Apple Soda", "Orange Barly", "Cream Soda", "EGB", "EGB Lite", "Lemonade", "Necto", "Orange Crush", "Soda", "Tonic", "Twistee Peach", "Twistee Apple", "Bitter Lemon", "Ginger Ale", "Wild Elephant" }));
        Btl_cat1.setMinimumSize(new java.awt.Dimension(140, 30));
        Btl_cat1.setPreferredSize(new java.awt.Dimension(140, 30));
        Btl_cat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btl_cat1ActionPerformed(evt);
            }
        });
        jPanel1.add(Btl_cat1);
        Btl_cat1.setBounds(260, 220, 170, 30);

        Qty1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Qty1.setForeground(new java.awt.Color(255, 255, 255));
        Qty1.setText("Quantity");
        Qty1.setMinimumSize(new java.awt.Dimension(60, 30));
        Qty1.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel1.add(Qty1);
        Qty1.setBounds(160, 400, 60, 30);

        invoice.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        invoice.setForeground(new java.awt.Color(255, 255, 255));
        invoice.setText("Invoice No");
        invoice.setMinimumSize(new java.awt.Dimension(60, 30));
        invoice.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel1.add(invoice);
        invoice.setBounds(580, 220, 60, 30);

        invoice_txt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        invoice_txt.setMinimumSize(new java.awt.Dimension(140, 30));
        invoice_txt.setPreferredSize(new java.awt.Dimension(140, 30));
        invoice_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoice_txtActionPerformed(evt);
            }
        });
        jPanel1.add(invoice_txt);
        invoice_txt.setBounds(680, 220, 170, 30);

        stck.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        stck.setForeground(new java.awt.Color(255, 255, 255));
        stck.setText("Stock Date");
        stck.setMinimumSize(new java.awt.Dimension(60, 30));
        stck.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel1.add(stck);
        stck.setBounds(160, 320, 60, 30);

        time1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        time1.setForeground(new java.awt.Color(255, 255, 255));
        time1.setText("time");
        jPanel1.add(time1);
        time1.setBounds(705, 0, 60, 20);

        date1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("date");
        jPanel1.add(date1);
        date1.setBounds(705, 14, 60, 20);

        backLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backbtn.png"))); // NOI18N
        backLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLblMouseClicked(evt);
            }
        });
        jPanel1.add(backLbl);
        backLbl.setBounds(930, 10, 25, 25);

        lgOutLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/logoutbtn.png"))); // NOI18N
        jPanel1.add(lgOutLbl);
        lgOutLbl.setBounds(960, 10, 25, 25);

        BtlSizeLbl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        BtlSizeLbl.setForeground(new java.awt.Color(255, 255, 255));
        BtlSizeLbl.setText("Bottle Size");
        BtlSizeLbl.setMinimumSize(new java.awt.Dimension(60, 30));
        BtlSizeLbl.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel1.add(BtlSizeLbl);
        BtlSizeLbl.setBounds(160, 120, 60, 30);

        btlCatLbl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btlCatLbl.setForeground(new java.awt.Color(255, 255, 255));
        btlCatLbl.setText("Category");
        btlCatLbl.setMinimumSize(new java.awt.Dimension(60, 30));
        btlCatLbl.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel1.add(btlCatLbl);
        btlCatLbl.setBounds(160, 220, 60, 30);

        StckDateChooser.setDateFormatString("yyyy-MMM-d");
        StckDateChooser.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        StckDateChooser.setMinimumSize(new java.awt.Dimension(140, 30));
        StckDateChooser.setPreferredSize(new java.awt.Dimension(140, 30));
        jPanel1.add(StckDateChooser);
        StckDateChooser.setBounds(260, 310, 170, 30);

        Qty_txt1.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        Qty_txt1.setMinimumSize(new java.awt.Dimension(140, 30));
        Qty_txt1.setPreferredSize(new java.awt.Dimension(140, 30));
        Qty_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Qty_txt1ActionPerformed(evt);
            }
        });
        jPanel1.add(Qty_txt1);
        Qty_txt1.setBounds(260, 400, 170, 30);

        priceLbl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        priceLbl.setForeground(new java.awt.Color(255, 255, 255));
        priceLbl.setText("Unit Price");
        priceLbl.setMinimumSize(new java.awt.Dimension(60, 30));
        priceLbl.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel1.add(priceLbl);
        priceLbl.setBounds(580, 310, 60, 30);

        price_Txt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        price_Txt.setMinimumSize(new java.awt.Dimension(140, 30));
        price_Txt.setPreferredSize(new java.awt.Dimension(140, 30));
        jPanel1.add(price_Txt);
        price_Txt.setBounds(680, 310, 170, 30);

        discount_lbl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        discount_lbl.setForeground(new java.awt.Color(255, 255, 255));
        discount_lbl.setText("Discount");
        discount_lbl.setMinimumSize(new java.awt.Dimension(60, 30));
        discount_lbl.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel1.add(discount_lbl);
        discount_lbl.setBounds(580, 120, 60, 30);

        totVal_lbl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        totVal_lbl.setForeground(new java.awt.Color(255, 255, 255));
        totVal_lbl.setText("Total Value");
        totVal_lbl.setMinimumSize(new java.awt.Dimension(60, 30));
        totVal_lbl.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel1.add(totVal_lbl);
        totVal_lbl.setBounds(580, 400, 60, 30);

        totVal_txt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        totVal_txt.setMinimumSize(new java.awt.Dimension(140, 30));
        totVal_txt.setPreferredSize(new java.awt.Dimension(140, 30));
        totVal_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totVal_txtActionPerformed(evt);
            }
        });
        jPanel1.add(totVal_txt);
        totVal_txt.setBounds(680, 400, 170, 30);

        discount_txt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        discount_txt.setMinimumSize(new java.awt.Dimension(140, 30));
        discount_txt.setPreferredSize(new java.awt.Dimension(140, 30));
        jPanel1.add(discount_txt);
        discount_txt.setBounds(680, 120, 170, 30);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Purchasing Order");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 20, 300, 30);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(140, 80, 730, 380);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/minimizebtn.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(900, 10, 25, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/closebtn.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(990, 10, 25, 25);

        bg.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backsup.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(0, 0, 1024, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "ok");
        size = (String) btl_size1.getSelectedItem();
        category = (String) Btl_cat1.getSelectedItem();
        qty = Qty_txt1.getText();
        invoiceNo = invoice_txt.getText();
        //date = StckDateChooser.getDateFormatString();
        date=((JTextField)StckDateChooser.getDateEditor().getUiComponent()).getText();
        price = price_Txt.getText();
        
        try {
            String sql = "INSERT INTO `purchasing`(size,category,qty,invoiceNo,date,price)VALUES('"+size+"','"+category+"','"+qty+"','"+invoiceNo+"','"+date+"','"+price+"')";
            
            pst= con.prepareStatement(sql);
            pst.execute();
            
            tableLoad();
        } 
        catch (Exception e) 
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_Add1ActionPerformed

    private void invoice_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoice_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoice_txtActionPerformed

    private void purch_tbl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purch_tbl1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_purch_tbl1MouseEntered

    private void purch_tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purch_tbl1MouseClicked
        
    }//GEN-LAST:event_purch_tbl1MouseClicked

    private void Clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear1ActionPerformed
       
        DefaultTableModel model = (DefaultTableModel) purch_tbl1.getModel();
        
        model.setRowCount(0);
        
         btl_size1.setSelectedItem("Bottle Size");
         Btl_cat1.setSelectedItem("Bottle Caregory");
         Qty_txt1.setText("0");
         invoice_txt.setText("");
         StckDateChooser.setDateFormatString("");
         price_Txt.setText("");
    }//GEN-LAST:event_Clear1ActionPerformed

    private void backLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLblMouseClicked
        main ma = new main();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backLblMouseClicked

    private void Btl_cat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btl_cat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btl_cat1ActionPerformed

    private void Qty_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Qty_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Qty_txt1ActionPerformed

    private void totVal_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totVal_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totVal_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchasing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchasing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add1;
    private javax.swing.JLabel BtlSizeLbl;
    private javax.swing.JComboBox<String> Btl_cat1;
    private javax.swing.JButton Clear1;
    private javax.swing.JLabel Qty1;
    private javax.swing.JTextField Qty_txt1;
    private com.toedter.calendar.JDateChooser StckDateChooser;
    private javax.swing.JLabel backLbl;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btlCatLbl;
    private javax.swing.JComboBox<String> btl_size1;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel discount_lbl;
    private javax.swing.JTextField discount_txt;
    private javax.swing.JLabel invoice;
    private javax.swing.JTextField invoice_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lgOutLbl;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JTextField price_Txt;
    private javax.swing.JTable purch_tbl1;
    private javax.swing.JLabel stck;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel totVal_lbl;
    private javax.swing.JTextField totVal_txt;
    // End of variables declaration//GEN-END:variables
}
