/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gehan;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AccountAnalysis extends javax.swing.JFrame {
 ResultSet rs;
    PreparedStatement pst;
    Statement st;

    GetDBConnection1 dbc = new GetDBConnection1(); //connect to database
    DefaultTableModel model;
    DefaultListModel modellist;
    int sCount; int pyCount=0; int oCount=0;
    int pCount=0; int vCount=0;
    DateFormat df = DateFormat.getDateInstance();
    public static String date = null;
     public static Double amount = 0.0;
      public static Double totalC = 0.0;
       public static Double totalD = 0.0;
       public static Double Income = 0.0;
    public AccountAnalysis() {
        initComponents();
        
        try {
             new Thread(new Runnable() {

            @Override
            public void run() {
                java.util.Date d = new java.util.Date();
                SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

                String s2 = sd.format(d);
                date1.setText(s2);

            }
        }).start();
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    java.util.Date d = new java.util.Date();
                    String s = d.toString();
                    String ar[] = s.split(" ");
                    time1.setText(ar[3]);

                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        date1 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        minimizedbtn = new javax.swing.JLabel();
        backbtn = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        logoutbtn = new javax.swing.JLabel();
        closebtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        payroll = new javax.swing.JLabel();
        purches = new javax.swing.JLabel();
        vehical = new javax.swing.JLabel();
        other = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        salesProgress = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        salesval = new javax.swing.JLabel();
        cashbookID = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        DebiitProgress = new javax.swing.JProgressBar();
        CreditProgress = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IncomeProgress = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        creditL = new javax.swing.JLabel();
        debitL = new javax.swing.JLabel();
        incomeL = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        delete2 = new javax.swing.JButton();
        delete3 = new javax.swing.JButton();
        bglbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 10));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setSize(new java.awt.Dimension(1024, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("date");
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 60, -1));

        time1.setBackground(new java.awt.Color(255, 255, 255));
        time1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        time1.setForeground(new java.awt.Color(255, 255, 255));
        time1.setText("time");
        jPanel1.add(time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 50, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reports");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 20, 70, 30));

        minimizedbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/minimizebtn.png"))); // NOI18N
        minimizedbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizedbtnMouseClicked(evt);
            }
        });
        jPanel1.add(minimizedbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 25, 25));

        backbtn.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(204, 204, 204));
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backbtn.png"))); // NOI18N
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 25, 25));

        jDateChooser1.setDateFormatString("yyyy-MMM-d ");
        jDateChooser1.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 110, 20));

        logoutbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/logoutbtn.png"))); // NOI18N
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
        });
        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 25, 25));

        closebtn.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        closebtn.setForeground(new java.awt.Color(204, 204, 204));
        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/closebtn.png"))); // NOI18N
        closebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closebtn.setPreferredSize(new java.awt.Dimension(30, 30));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        jPanel1.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 25, 25));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Payroll ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 30));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Purchasing ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 30));

        payroll.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        payroll.setForeground(new java.awt.Color(102, 102, 102));
        payroll.setText("value");
        jPanel2.add(payroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 130, 30));

        purches.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        purches.setForeground(new java.awt.Color(102, 102, 102));
        purches.setText("value");
        jPanel2.add(purches, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 130, 30));

        vehical.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        vehical.setForeground(new java.awt.Color(102, 102, 102));
        vehical.setText("value");
        jPanel2.add(vehical, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 130, 30));

        other.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        other.setForeground(new java.awt.Color(102, 102, 102));
        other.setText("value");
        jPanel2.add(other, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 130, 30));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Vehicle");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText(" Other");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 320, 190));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(salesProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 290, 30));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Sales");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, 40));

        salesval.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        salesval.setForeground(new java.awt.Color(102, 102, 102));
        salesval.setText("value");
        jPanel3.add(salesval, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 80, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 360, 190));

        cashbookID.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cashbookID.setForeground(new java.awt.Color(255, 255, 255));
        cashbookID.setText("Date");
        jPanel1.add(cashbookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 50, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(DebiitProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 290, 30));
        jPanel5.add(CreditProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Credit");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 100, 30));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Debit");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 100, 30));
        jPanel5.add(IncomeProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 290, 30));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Income");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 100, 30));

        creditL.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        creditL.setForeground(new java.awt.Color(102, 102, 102));
        creditL.setText("value");
        jPanel5.add(creditL, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 100, 30));

        debitL.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        debitL.setForeground(new java.awt.Color(102, 102, 102));
        debitL.setText("value");
        jPanel5.add(debitL, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 100, 30));

        incomeL.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        incomeL.setForeground(new java.awt.Color(102, 102, 102));
        incomeL.setText("value");
        jPanel5.add(incomeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 100, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 710, 155));

        delete.setBackground(new java.awt.Color(0, 153, 0));
        delete.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Bank Report");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 170, 130, -1));

        delete1.setBackground(new java.awt.Color(0, 153, 0));
        delete1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        delete1.setForeground(new java.awt.Color(255, 255, 255));
        delete1.setText("Analyse");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        jPanel1.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 100, -1));

        delete2.setBackground(new java.awt.Color(0, 153, 0));
        delete2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        delete2.setForeground(new java.awt.Color(255, 255, 255));
        delete2.setText("Ledger Report");
        delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ActionPerformed(evt);
            }
        });
        jPanel1.add(delete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 130, -1));

        delete3.setBackground(new java.awt.Color(0, 153, 0));
        delete3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        delete3.setForeground(new java.awt.Color(255, 255, 255));
        delete3.setText("Cash Report");
        delete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete3ActionPerformed(evt);
            }
        });
        jPanel1.add(delete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 130, 130, -1));

        bglbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backmain.jpg"))); // NOI18N
        jPanel1.add(bglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   
    }//GEN-LAST:event_formWindowOpened

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
     
           ReportView1 z=new ReportView1("C:\\Users\\User\\Desktop\\Final ERP Sysytm\\report5.jasper");
        z.setVisible(true);
          
          
    }//GEN-LAST:event_deleteActionPerformed

    private void minimizedbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizedbtnMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizedbtnMouseClicked

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        Accounts accounts = new Accounts();
        accounts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnMouseClicked

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_closebtnMouseClicked

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        // TODO add your handling code here:
        
                
        date=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        // String  day=((JTextField)jDateChooser4.getDateEditor().getUiComponent()).getText();
         System.out.println(date);
          String query1=" SELECT COUNT(ledger_id) FROM ledger_book where ledgerType = 'Sale' and date = '"+ date +"'" ;
          String query2=" SELECT COUNT(ledger_id) as pcount FROM ledger_book where ledgerType= 'Purchasing' and date='"+date+"'";
          String query3=" SELECT COUNT(ledger_id) as pycount FROM ledger_book where ledgerType= 'Payroll' and date='"+date+"'";
          String query4=" SELECT COUNT(ledger_id) as vcount FROM ledger_book where ledgerType= 'Vehicle' and date='"+date+"'";
          String query5=" SELECT COUNT(ledger_id) as ocount FROM ledger_book where ledgerType= 'Other' and date='"+date+"'";
          String query6=" SELECT amount FROM cash_book where amountType= 'Credit' and date='"+date+"'";
          String query7=" SELECT amount FROM cash_book where amountType= 'Debit' and date='"+date+"'";
          
          try
          {
              pst = dbc.con.prepareStatement(query1);
              this.rs = this.pst.executeQuery();
            
              while(rs.next())
            {  
                sCount=rs.getInt("COUNT(ledger_id)");
                System.out.println(sCount);
                salesval.setText(Integer.toString(sCount));
                salesProgress.setValue(sCount*5); 
                
            }
              
              pst = dbc.con.prepareStatement(query2);
             this.rs = this.pst.executeQuery();
            
              while(rs.next())
            {  
                pCount=rs.getInt("pcount");
                purches.setText(Integer.toString(pCount));
               
            }
              
                   pst = dbc.con.prepareStatement(query3);
             this.rs = this.pst.executeQuery();
            
              while(rs.next())
            {  
                pyCount=rs.getInt("pycount");
                payroll.setText(Integer.toString(pyCount));
               
            }
              
                   pst = dbc.con.prepareStatement(query4);
             this.rs = this.pst.executeQuery();
            
              while(rs.next())
            {  
                vCount=rs.getInt("vcount");
                vehical.setText(Integer.toString(vCount));
               
            }
              
                   pst = dbc.con.prepareStatement(query5);
             this.rs = this.pst.executeQuery();
            
              while(rs.next())
            {  
                oCount=rs.getInt("ocount");
                other.setText(Integer.toString(oCount));
               
            }
              
              
                     pst = dbc.con.prepareStatement(query6);
             this.rs = this.pst.executeQuery();
            
              while(rs.next())
            {  
                amount=rs.getDouble("amount");
                totalC=totalC+amount;
               
            }
              creditL.setText(totalC.toString());
              CreditProgress.setValue(Integer.valueOf(totalC.intValue()/1000));
              
                       pst = dbc.con.prepareStatement(query7);
             this.rs = this.pst.executeQuery();
            
              while(rs.next())
            {  
                amount=rs.getDouble("amount");
                totalD=totalD+amount;
                
               
            }
              debitL.setText(totalD.toString());
              DebiitProgress.setValue(Integer.valueOf(totalD.intValue()/1000));
              
              Income=totalC-totalD;
              incomeL.setText(Income.toString());
               IncomeProgress.setValue(Integer.valueOf(Income.intValue()/1000));
              
              
              
              
              
              
          }
          catch(Exception e)
          {
              System.out.println(e);
          }
          
          
        
    }//GEN-LAST:event_delete1ActionPerformed

    private void delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ActionPerformed
        ReportView1 x =new ReportView1("C:\\Users\\User\\Desktop\\Final ERP Sysytm\\report3.jasper");
        x.setVisible(true);
    }//GEN-LAST:event_delete2ActionPerformed

    private void delete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete3ActionPerformed
        ReportView1 y =new ReportView1("C:\\Users\\User\\Desktop\\Final ERP Sysytm\\report4.jasper");
        y.setVisible(true);
    }//GEN-LAST:event_delete3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountAnalysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountAnalysis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar CreditProgress;
    private javax.swing.JProgressBar DebiitProgress;
    private javax.swing.JProgressBar IncomeProgress;
    private javax.swing.JLabel backbtn;
    private javax.swing.JLabel bglbl;
    private javax.swing.JLabel cashbookID;
    private javax.swing.JLabel closebtn;
    private javax.swing.JLabel creditL;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel debitL;
    private javax.swing.JButton delete;
    private javax.swing.JButton delete1;
    private javax.swing.JButton delete2;
    private javax.swing.JButton delete3;
    private javax.swing.JLabel incomeL;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logoutbtn;
    private javax.swing.JLabel minimizedbtn;
    private javax.swing.JLabel other;
    private javax.swing.JLabel payroll;
    private javax.swing.JLabel purches;
    private javax.swing.JProgressBar salesProgress;
    private javax.swing.JLabel salesval;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel vehical;
    // End of variables declaration//GEN-END:variables
}
