/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gehan;

import java.awt.Color;
import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author gEhan
 */
public class Add_Users extends javax.swing.JFrame {

     ResultSet rs;
    PreparedStatement pst;  
    Statement st;  
    
    
 GetDBConnection1 dbc = new GetDBConnection1(); //connect to database
    /**
     * Creates new form Add_Users
     */
    public Add_Users() {
        initComponents();
        
        try {
             new Thread(new Runnable() {

            @Override
            public void run() {
                java.util.Date d = new java.util.Date();
                SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

                String s2 = sd.format(d);
                date1.setText(s2);

            }
        }).start();
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    java.util.Date d = new java.util.Date();
                    String s = d.toString();
                    String ar[] = s.split(" ");
                    time1.setText(ar[3]);

                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
       
    }
    
    private static String fname = null;
    private static String lname = null;
    private static String post = null;
    private static String username = null;
    private static String password = null;
    private static String Cpassword = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minimizedbtn = new javax.swing.JLabel();
        closebtn = new javax.swing.JLabel();
        backbtn = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        combo_post = new javax.swing.JComboBox<>();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        lastName = new javax.swing.JLabel();
        AddUsers = new javax.swing.JButton();
        userName = new javax.swing.JLabel();
        passwordlbl = new javax.swing.JLabel();
        postlbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddUserTable = new javax.swing.JTable();
        date1 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        txt_Conf_password = new javax.swing.JPasswordField();
        Confpasswordlbl = new javax.swing.JLabel();
        bgAddUsers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 10));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Users");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 20, 90, 30);

        minimizedbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/minimizebtn.png"))); // NOI18N
        minimizedbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizedbtnMouseClicked(evt);
            }
        });
        jPanel1.add(minimizedbtn);
        minimizedbtn.setBounds(900, 10, 25, 25);

        closebtn.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        closebtn.setForeground(new java.awt.Color(204, 204, 204));
        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/closebtn.png"))); // NOI18N
        closebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closebtn.setPreferredSize(new java.awt.Dimension(30, 30));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        jPanel1.add(closebtn);
        closebtn.setBounds(990, 10, 25, 25);

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backbtn.png"))); // NOI18N
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        jPanel1.add(backbtn);
        backbtn.setBounds(930, 10, 25, 25);

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/logoutbtn.png"))); // NOI18N
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        jPanel1.add(logoutBtn);
        logoutBtn.setBounds(960, 10, 25, 25);

        firstName.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        firstName.setForeground(new java.awt.Color(255, 255, 255));
        firstName.setText("First Name");
        jPanel1.add(firstName);
        firstName.setBounds(340, 110, 130, 25);

        txt_fname.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_fname.setMinimumSize(new java.awt.Dimension(180, 22));
        txt_fname.setPreferredSize(new java.awt.Dimension(180, 26));
        txt_fname.setSelectionColor(new java.awt.Color(0, 153, 0));
        jPanel1.add(txt_fname);
        txt_fname.setBounds(470, 110, 180, 28);

        txt_lname.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_lname.setMinimumSize(new java.awt.Dimension(180, 25));
        txt_lname.setPreferredSize(new java.awt.Dimension(180, 30));
        txt_lname.setSelectionColor(new java.awt.Color(0, 153, 0));
        jPanel1.add(txt_lname);
        txt_lname.setBounds(470, 160, 180, 28);

        combo_post.setBackground(new java.awt.Color(0, 153, 0));
        combo_post.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        combo_post.setForeground(new java.awt.Color(255, 255, 255));
        combo_post.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Post", "Operator", "Manager", "Administrator" }));
        combo_post.setMinimumSize(new java.awt.Dimension(120, 25));
        combo_post.setPreferredSize(new java.awt.Dimension(120, 25));
        jPanel1.add(combo_post);
        combo_post.setBounds(470, 210, 180, 28);

        txt_username.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_username.setMinimumSize(new java.awt.Dimension(180, 25));
        txt_username.setPreferredSize(new java.awt.Dimension(180, 30));
        txt_username.setSelectionColor(new java.awt.Color(0, 153, 0));
        jPanel1.add(txt_username);
        txt_username.setBounds(470, 260, 180, 28);

        txt_password.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_password.setMinimumSize(new java.awt.Dimension(180, 25));
        txt_password.setPreferredSize(new java.awt.Dimension(180, 30));
        txt_password.setSelectionColor(new java.awt.Color(0, 153, 0));
        jPanel1.add(txt_password);
        txt_password.setBounds(470, 320, 180, 28);

        lastName.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lastName.setForeground(new java.awt.Color(255, 255, 255));
        lastName.setText("Last Name");
        jPanel1.add(lastName);
        lastName.setBounds(340, 160, 130, 25);

        AddUsers.setBackground(new java.awt.Color(0, 153, 0));
        AddUsers.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        AddUsers.setForeground(new java.awt.Color(255, 255, 255));
        AddUsers.setText("Add User");
        AddUsers.setMaximumSize(new java.awt.Dimension(80, 22));
        AddUsers.setMinimumSize(new java.awt.Dimension(80, 22));
        AddUsers.setPreferredSize(new java.awt.Dimension(80, 22));
        AddUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUsersMouseClicked(evt);
            }
        });
        AddUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUsersActionPerformed(evt);
            }
        });
        jPanel1.add(AddUsers);
        AddUsers.setBounds(510, 410, 100, 25);

        userName.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText("User Name");
        jPanel1.add(userName);
        userName.setBounds(340, 260, 130, 25);

        passwordlbl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        passwordlbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordlbl.setText("Password");
        jPanel1.add(passwordlbl);
        passwordlbl.setBounds(340, 320, 130, 25);

        postlbl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        postlbl.setForeground(new java.awt.Color(255, 255, 255));
        postlbl.setText("Post");
        jPanel1.add(postlbl);
        postlbl.setBounds(340, 210, 130, 25);

        AddUserTable.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        AddUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "User Name", "Password"
            }
        ));
        AddUserTable.setSelectionBackground(new java.awt.Color(0, 153, 0));
        jScrollPane1.setViewportView(AddUserTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(200, 460, 620, 120);

        date1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("date");
        jPanel1.add(date1);
        date1.setBounds(720, 10, 80, 20);

        time1.setBackground(new java.awt.Color(255, 255, 255));
        time1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        time1.setForeground(new java.awt.Color(255, 255, 255));
        time1.setText("time");
        jPanel1.add(time1);
        time1.setBounds(720, 0, 80, 20);

        txt_Conf_password.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        txt_Conf_password.setMinimumSize(new java.awt.Dimension(180, 25));
        txt_Conf_password.setPreferredSize(new java.awt.Dimension(180, 30));
        txt_Conf_password.setSelectionColor(new java.awt.Color(0, 153, 0));
        jPanel1.add(txt_Conf_password);
        txt_Conf_password.setBounds(470, 360, 180, 28);

        Confpasswordlbl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Confpasswordlbl.setForeground(new java.awt.Color(255, 255, 255));
        Confpasswordlbl.setText("Confirm Password");
        jPanel1.add(Confpasswordlbl);
        Confpasswordlbl.setBounds(340, 360, 130, 25);

        bgAddUsers.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        bgAddUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backsup.jpg"))); // NOI18N
        jPanel1.add(bgAddUsers);
        bgAddUsers.setBounds(0, 0, 1024, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        Admin_Home adh = new Admin_Home();
        adh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnMouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        Login login = new Login ();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void AddUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUsersMouseClicked
        // TODO add your handling code here:
        
         DefaultTableModel model=(DefaultTableModel) AddUserTable.getModel();
       
        fname = txt_fname.getText();
        lname = txt_lname.getText();
        post = (String) combo_post.getSelectedItem();
        username = txt_username.getText();
        password = txt_password.getText();
        Cpassword = txt_Conf_password.getText();
       
      
       
       
       
        if(fname.equals("") || lname.equals("") ||username.equals("") || password.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Fields cannot be empty.");
            
        }
        
        
        else if(!fname.matches("[a-zA-Z]+") || !lname.matches("[a-zA-Z]+") )
        {
            JOptionPane.showMessageDialog(null,"Name cannot contain numbers or special characters.");
            txt_fname.setText("");
            txt_lname.setText("");
        }
        else if(post.equals("Post"))
        {
            JOptionPane.showMessageDialog(null,"Post cannot cannot be empty.");
            combo_post.requestFocusInWindow();
        }
        else if( username.length() < 6)
        {
            JOptionPane.showMessageDialog(null,"Username must have atleast 6 characters");
            txt_username.requestFocusInWindow();
            txt_username.setForeground(Color.red);
            
        }
        
        else if( password.length() < 5)
        {
            JOptionPane.showMessageDialog(null,"Password must have atleast 5 characters");
            txt_password.requestFocusInWindow();
            txt_password.setText("");
        }
        else if(!Cpassword.matches(password))
        {
            JOptionPane.showMessageDialog(null,"Password id not matched,Enter Password again!");
            txt_Conf_password.requestFocusInWindow();
            txt_Conf_password.setForeground(Color.red);
            txt_Conf_password.setText("");
        }
        else
        {
         try {
              
          String query1="INSERT INTO users values('"+fname+"','"+lname+"','"+post+"','"+username+"','"+password+"')";
   
            
             pst=dbc.con.prepareStatement(query1);
            
            pst.execute();
            
            model.addRow(new Object[]{fname,lname,post,username,password});
        JOptionPane.showConfirmDialog(null, "Successfully Added");
    
             txt_fname.setText("");
            txt_lname.setText("");
            combo_post.setSelectedItem("Post");
            txt_username.setText("");
            txt_password.setText("");
            txt_Conf_password.setText("");
      }
      catch(Exception e){
          System.out.println(e);
      }
        
        
      }                             
    }//GEN-LAST:event_AddUsersMouseClicked

    private void minimizedbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizedbtnMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizedbtnMouseClicked

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_closebtnMouseClicked

    private void AddUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AddUserTable;
    private javax.swing.JButton AddUsers;
    private javax.swing.JLabel Confpasswordlbl;
    private javax.swing.JLabel backbtn;
    private javax.swing.JLabel bgAddUsers;
    private javax.swing.JLabel closebtn;
    private javax.swing.JComboBox<String> combo_post;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel minimizedbtn;
    private javax.swing.JLabel passwordlbl;
    private javax.swing.JLabel postlbl;
    private javax.swing.JLabel time1;
    private javax.swing.JPasswordField txt_Conf_password;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
