/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gehan;


import java.sql.*;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author gEhan
 */
public class BankBook extends javax.swing.JFrame {
    ResultSet rs;
    PreparedStatement pst;  
    Statement st;  
    
    
 GetDBConnection1 dbc = new GetDBConnection1(); //connect to database
    /**
     * Creates new form BankBook
     */
    public BankBook() {
        initComponents();
    try {
             new Thread(new Runnable() {

            @Override
            public void run() {
                java.util.Date d = new java.util.Date();
                SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

                String s2 = sd.format(d);
                date1.setText(s2);

            }
        }).start();
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    java.util.Date d = new java.util.Date();
                    String s = d.toString();
                    String ar[] = s.split(" ");
                    time1.setText(ar[3]);

                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
         
    }
    public static String bankbookID = null;
     public static String ledgerbookID = null;
    public static String date = null;
     public static String Chqnum = null;
   
    
    public static Double amount = 0.0;
    public static String des = null;
     DateFormat dfc = DateFormat.getDateInstance();
     private int idAutoGenerate()
    {
        String queryid = "SELECT MAX(bankbook_id) FROM bank_book";
        int nextappid;

        try {
            pst = dbc.con.prepareStatement(queryid);
            rs = this.pst.executeQuery();

            while (rs.next()) {
                nextappid = rs.getInt(1);
                Integer appid = nextappid+1;
                return appid;
               
            }

        } 
        catch (SQLException err) 
        {
            JOptionPane.showMessageDialog(this, err);
        }       
        return 0;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JLabel();
        backbtn = new javax.swing.JLabel();
        minimizedbtn = new javax.swing.JLabel();
        closebtn = new javax.swing.JLabel();
        bankBookIDText = new javax.swing.JTextField();
        Date = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        addbtn = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cashBooktable = new javax.swing.JScrollPane();
        bankBookTable = new javax.swing.JTable();
        searchBUtton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ledgerTable = new javax.swing.JTable();
        searchLedger = new javax.swing.JLabel();
        rupeeslbl = new javax.swing.JLabel();
        rupees = new javax.swing.JTextField();
        time1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        bankbookID1 = new javax.swing.JLabel();
        clearBankBook1 = new javax.swing.JButton();
        bankBookIdGenerate = new javax.swing.JButton();
        bankbookID2 = new javax.swing.JLabel();
        ledgerBookIDtxt = new javax.swing.JTextField();
        bankbookID3 = new javax.swing.JLabel();
        chequeIDtxt = new javax.swing.JTextField();
        Date1 = new javax.swing.JLabel();
        searchLedger1 = new javax.swing.JButton();
        ledgerBookClear = new javax.swing.JButton();
        spectator = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(175, 10));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bank Book");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 20, 100, 25);

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/logoutbtn.png"))); // NOI18N
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
        });
        jPanel1.add(logoutbtn);
        logoutbtn.setBounds(960, 10, 25, 25);

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backbtn.png"))); // NOI18N
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        jPanel1.add(backbtn);
        backbtn.setBounds(930, 10, 25, 25);

        minimizedbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/minimizebtn.png"))); // NOI18N
        minimizedbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizedbtnMouseClicked(evt);
            }
        });
        jPanel1.add(minimizedbtn);
        minimizedbtn.setBounds(900, 10, 25, 25);

        closebtn.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        closebtn.setForeground(new java.awt.Color(204, 204, 204));
        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/closebtn.png"))); // NOI18N
        closebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closebtn.setPreferredSize(new java.awt.Dimension(30, 30));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        jPanel1.add(closebtn);
        closebtn.setBounds(990, 10, 25, 25);

        bankBookIDText.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        bankBookIDText.setForeground(new java.awt.Color(0, 102, 0));
        bankBookIDText.setSelectionColor(new java.awt.Color(0, 153, 0));
        jPanel1.add(bankBookIDText);
        bankBookIDText.setBounds(180, 130, 130, 28);

        Date.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        Date.setText("Date");
        jPanel1.add(Date);
        Date.setBounds(80, 250, 100, 28);

        description.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        description.setForeground(new java.awt.Color(255, 255, 255));
        description.setText("Description");
        jPanel1.add(description);
        description.setBounds(80, 330, 100, 28);

        descriptionText.setColumns(20);
        descriptionText.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        descriptionText.setForeground(new java.awt.Color(0, 102, 0));
        descriptionText.setRows(5);
        descriptionText.setSelectionColor(new java.awt.Color(0, 153, 0));
        jScrollPane1.setViewportView(descriptionText);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(180, 330, 230, 86);

        addbtn.setBackground(new java.awt.Color(0, 153, 0));
        addbtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addbtn);
        addbtn.setBounds(180, 440, 70, 25);

        update.setBackground(new java.awt.Color(0, 153, 0));
        update.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(260, 440, 70, 25);

        delete.setBackground(new java.awt.Color(0, 153, 0));
        delete.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(340, 440, 65, 25);

        bankBookTable.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        bankBookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bank Book ID", "Chequ ID", "Date", "Description", "Amount"
            }
        ));
        bankBookTable.setGridColor(new java.awt.Color(0, 153, 0));
        bankBookTable.setSelectionBackground(new java.awt.Color(0, 153, 0));
        bankBookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bankBookTableMouseClicked(evt);
            }
        });
        cashBooktable.setViewportView(bankBookTable);

        jPanel1.add(cashBooktable);
        cashBooktable.setBounds(200, 500, 640, 130);

        searchBUtton.setBackground(new java.awt.Color(0, 153, 0));
        searchBUtton.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        searchBUtton.setForeground(new java.awt.Color(255, 255, 255));
        searchBUtton.setText("Search");
        searchBUtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBUttonActionPerformed(evt);
            }
        });
        jPanel1.add(searchBUtton);
        searchBUtton.setBounds(360, 640, 90, 25);

        jScrollPane2.setBackground(new java.awt.Color(0, 153, 0));

        ledgerTable.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        ledgerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ledger ID", "Date", "Ledger Type", "Amount Type", "amount", "des"
            }
        ));
        ledgerTable.setSelectionBackground(new java.awt.Color(0, 153, 0));
        ledgerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ledgerTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ledgerTable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(520, 260, 440, 160);

        searchLedger.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        searchLedger.setForeground(new java.awt.Color(255, 255, 255));
        searchLedger.setText("Search Ledgers");
        jPanel1.add(searchLedger);
        searchLedger.setBounds(710, 130, 90, 30);

        rupeeslbl.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rupeeslbl.setForeground(new java.awt.Color(255, 255, 255));
        rupeeslbl.setText("Rs.");
        jPanel1.add(rupeeslbl);
        rupeeslbl.setBounds(80, 290, 100, 28);

        rupees.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        rupees.setForeground(new java.awt.Color(0, 102, 0));
        rupees.setSelectionColor(new java.awt.Color(0, 153, 0));
        rupees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rupeesActionPerformed(evt);
            }
        });
        jPanel1.add(rupees);
        rupees.setBounds(180, 290, 130, 28);

        time1.setBackground(new java.awt.Color(255, 255, 255));
        time1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        time1.setForeground(new java.awt.Color(255, 255, 255));
        time1.setText("time");
        jPanel1.add(time1);
        time1.setBounds(720, 0, 60, 20);

        date1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("date");
        jPanel1.add(date1);
        date1.setBounds(720, 10, 70, 20);

        jDateChooser1.setDateFormatString("yyyy-MMM-d ");
        jDateChooser1.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(180, 250, 130, 30);

        jDateChooser2.setDateFormatString("yyyy-MMM-d ");
        jDateChooser2.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel1.add(jDateChooser2);
        jDateChooser2.setBounds(740, 170, 110, 30);

        bankbookID1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        bankbookID1.setForeground(new java.awt.Color(255, 255, 255));
        bankbookID1.setText("Bank Book ID");
        jPanel1.add(bankbookID1);
        bankbookID1.setBounds(80, 130, 100, 28);

        clearBankBook1.setBackground(new java.awt.Color(0, 153, 0));
        clearBankBook1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        clearBankBook1.setForeground(new java.awt.Color(255, 255, 255));
        clearBankBook1.setText("Clear");
        clearBankBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBankBook1ActionPerformed(evt);
            }
        });
        jPanel1.add(clearBankBook1);
        clearBankBook1.setBounds(590, 640, 90, 25);

        bankBookIdGenerate.setBackground(new java.awt.Color(0, 153, 0));
        bankBookIdGenerate.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        bankBookIdGenerate.setForeground(new java.awt.Color(255, 255, 255));
        bankBookIdGenerate.setText("Generate");
        bankBookIdGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankBookIdGenerateActionPerformed(evt);
            }
        });
        jPanel1.add(bankBookIdGenerate);
        bankBookIdGenerate.setBounds(330, 130, 79, 25);

        bankbookID2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        bankbookID2.setForeground(new java.awt.Color(255, 255, 255));
        bankbookID2.setText("Ledger Book ID");
        jPanel1.add(bankbookID2);
        bankbookID2.setBounds(80, 170, 100, 28);

        ledgerBookIDtxt.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ledgerBookIDtxt.setForeground(new java.awt.Color(0, 102, 0));
        ledgerBookIDtxt.setSelectionColor(new java.awt.Color(0, 153, 0));
        jPanel1.add(ledgerBookIDtxt);
        ledgerBookIDtxt.setBounds(180, 170, 130, 28);

        bankbookID3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        bankbookID3.setForeground(new java.awt.Color(255, 255, 255));
        bankbookID3.setText("Cheque ID");
        jPanel1.add(bankbookID3);
        bankbookID3.setBounds(80, 210, 100, 28);

        chequeIDtxt.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        chequeIDtxt.setForeground(new java.awt.Color(0, 102, 0));
        chequeIDtxt.setSelectionColor(new java.awt.Color(0, 153, 0));
        jPanel1.add(chequeIDtxt);
        chequeIDtxt.setBounds(180, 210, 130, 28);

        Date1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Date1.setForeground(new java.awt.Color(255, 255, 255));
        Date1.setText("Date");
        jPanel1.add(Date1);
        Date1.setBounds(670, 170, 80, 28);

        searchLedger1.setBackground(new java.awt.Color(0, 153, 0));
        searchLedger1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        searchLedger1.setForeground(new java.awt.Color(255, 255, 255));
        searchLedger1.setText("Search");
        searchLedger1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchLedger1ActionPerformed(evt);
            }
        });
        jPanel1.add(searchLedger1);
        searchLedger1.setBounds(650, 220, 90, 25);

        ledgerBookClear.setBackground(new java.awt.Color(0, 153, 0));
        ledgerBookClear.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        ledgerBookClear.setForeground(new java.awt.Color(255, 255, 255));
        ledgerBookClear.setText("Clear");
        ledgerBookClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ledgerBookClearActionPerformed(evt);
            }
        });
        jPanel1.add(ledgerBookClear);
        ledgerBookClear.setBounds(770, 220, 90, 25);

        spectator.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(spectator);
        spectator.setBounds(50, 100, 420, 380);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setAlignmentX(2.0F);
        jSeparator2.setAlignmentY(2.0F);
        jSeparator2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jSeparator2.setPreferredSize(new java.awt.Dimension(2, 5));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(490, 100, 510, 380);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backsup.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(0, 0, 1024, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked
        Login login = new Login ();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
       Accounts accounts = new Accounts();
       accounts.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backbtnMouseClicked

    private void rupeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rupeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rupeesActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
         
        DefaultTableModel model=(DefaultTableModel) bankBookTable.getModel();
       
       bankbookID = bankBookIDText.getText();
       ledgerbookID = ledgerBookIDtxt.getText();
       Chqnum=chequeIDtxt.getText();
       date = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
       amount = Double.parseDouble(rupees.getText());
       des = descriptionText.getText();
       
      
       
       
       
        if(bankbookID.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Bank Book ID cannot be empty!");
        }
        else
        {
        }
       
         try {
              
          String query1="INSERT INTO bank_book values('"+bankbookID+"','"+ledgerbookID+"','"+date+"','"+Chqnum+"','"+des+"','"+amount+"')";
   
            
             pst=dbc.con.prepareStatement(query1);
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Successfully Added");
            model.addRow(new Object[]{bankbookID,Chqnum, date, des, amount});
       
    
             bankBookIDText.setText("");
             ledgerBookIDtxt.setText("");
             descriptionText.setText("");
            ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(null);
             chequeIDtxt.setText("");
             rupees.setText("0.0");
      }
      catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
      }
        
   
    


    }//GEN-LAST:event_addbtnActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       // TODO add your handling code here:DefaultTableModel model=(DefaultTableModel) cashBookTable.getModel();
        DefaultTableModel model=(DefaultTableModel) bankBookTable.getModel();
         int x= JOptionPane.showConfirmDialog(null, "Do you really want to update?");
        if(x==0){
                        bankbookID = bankBookIDText.getText();
                        ledgerbookID = ledgerBookIDtxt.getText();
                        Chqnum=chequeIDtxt.getText();
                        date = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
                        amount = Double.parseDouble(rupees.getText());
                        des = descriptionText.getText();    

                        
                        
                       
                        String sql="Update bank_book SET  bankbook_id='"+  bankbookID +"' ,ledgerbook_id='"+ ledgerbookID +"' , date='"+date+"' ,ChecqNum='"+Chqnum+"' , description='"+des+"' , amount='"+amount+"'  WHERE bankbook_id='"+bankbookID+"' ";
           try{
                pst=dbc.con.prepareStatement(sql);
                
                pst.execute();
                JOptionPane.showMessageDialog(null, " error");
                JOptionPane.showConfirmDialog(null, "Updated Succesfully");
                model.addRow(new Object[]{bankbookID,Chqnum, date, des, amount});
            
            bankBookIDText.setText("");
             ledgerBookIDtxt.setText("");
             descriptionText.setText("");
             ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(null);
           //  Bdate.setDate(null);
             chequeIDtxt.setText("");
             rupees.setText("0.0");
           
           }
            catch(Exception e){}
        }  
           
    }//GEN-LAST:event_updateActionPerformed

    private void searchBUttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBUttonActionPerformed
        // TODO add your handling code here:
        
             bankbookID = bankBookIDText.getText();     
             date =((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
       
        try{
             
            
            String sql="Select * from bank_book where bankbook_id LIKE CONCAT('%','" +  bankbookID + "','%') and date='" +  date + "'  ";
         
            pst=dbc.con.prepareStatement(sql);
        
            rs=pst.executeQuery();
            
            while(rs.next()){

             
                bankbookID = rs.getString("bankbook_id");
                ledgerbookID = rs.getString("ledgerbook_id");
                date = rs.getString("date");
                Chqnum = rs.getString("ChecqNum");
               des = rs.getString("description");
               amount = rs.getDouble("amount");
               
             JOptionPane.showMessageDialog(null, "done ");
           
             
                
                DefaultTableModel model=(DefaultTableModel) bankBookTable.getModel();
                
                model.addRow(new Object[]{bankbookID,Chqnum,date , des, amount});
            }
        
        
        }
      catch(Exception e){}
    }//GEN-LAST:event_searchBUttonActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
        try{
            
            bankbookID = bankBookIDText.getText();     
             String sql = "delete  from bank_book where bankbook_id ='" + bankbookID + "'";
             pst = dbc.con.prepareStatement(sql);
             pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted !!!");
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, " error");
        }
    //---------delete from table------------------
        DefaultTableModel model=(DefaultTableModel) bankBookTable.getModel();
        model.removeRow(bankBookTable.getSelectedRow());

        //-----------reset textfields---------------
              bankBookIDText.setText("");
             ledgerBookIDtxt.setText("");
             descriptionText.setText("");
             ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(null);
            // Bdate.setDate(null);
             chequeIDtxt.setText("");
             rupees.setText("0.0");
    }//GEN-LAST:event_deleteActionPerformed

    private void bankBookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bankBookTableMouseClicked
        // TODO add your handling code here:
        
        int r=bankBookTable.getSelectedRow();
        
         bankbookID= bankBookTable.getValueAt(r, 0).toString();
       Chqnum= bankBookTable.getValueAt(r, 1).toString();  
       des = bankBookTable.getValueAt(r, 3).toString();
       String rupee= bankBookTable.getValueAt(r, 4).toString();
       
            bankBookIDText.setText(bankbookID);
             chequeIDtxt.setText(Chqnum);
             descriptionText.setText(des);
             ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(null);
             rupees.setText(rupee);
    }//GEN-LAST:event_bankBookTableMouseClicked

    private void clearBankBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBankBook1ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) bankBookTable.getModel();
                
        model.setRowCount(0);
           bankBookIDText.setText("");
             ledgerBookIDtxt.setText("");
             descriptionText.setText("");
            ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(null);
             chequeIDtxt.setText("");
             rupees.setText("0.0");
    }//GEN-LAST:event_clearBankBook1ActionPerformed

    private void bankBookIdGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankBookIdGenerateActionPerformed
        // TODO add your handling code here:
       Integer cashID = idAutoGenerate();  
       bankbookID = cashID.toString();
       
       bankBookIDText.setText(bankbookID); 
        
        
    }//GEN-LAST:event_bankBookIdGenerateActionPerformed

    private void searchLedger1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchLedger1ActionPerformed
        // TODO add your handling code here:
    date = ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
         
        try{
           
            String sql="Select * from ledger_book where  date='" +  date+ "' and paymentType ='Cheque'";

            pst=dbc.con.prepareStatement(sql);
       
            rs=pst.executeQuery();
      
            while(rs.next()){
                
                ledgerbookID = rs.getString("ledger_id");
              
                des = rs.getString("description");
                String amountTypeL = rs.getString("amountType");
                String ledgerTypeL = rs.getString("ledgerType");
               
                amount = rs.getDouble("amount");
            
                String rupeeL=(Double.toString(amount));
                
              

                DefaultTableModel model=(DefaultTableModel) ledgerTable.getModel();

                model.addRow(new Object[]{ledgerbookID, date, ledgerTypeL,  amountTypeL, rupeeL,des});
            
            }

        }
        catch(Exception e){}

    }//GEN-LAST:event_searchLedger1ActionPerformed

    private void ledgerBookClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ledgerBookClearActionPerformed
        DefaultTableModel model = (DefaultTableModel) ledgerTable.getModel();
       ((JTextField)jDateChooser2.getDateEditor().getUiComponent()).setText(null);
        model.setRowCount(0);

    }//GEN-LAST:event_ledgerBookClearActionPerformed

    private void ledgerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ledgerTableMouseClicked
          int r = ledgerTable.getSelectedRow();

        ledgerbookID = ledgerTable.getValueAt(r, 0).toString();
        date = ledgerTable.getValueAt(r, 1).toString();
     
        des = ledgerTable.getValueAt(r, 5).toString();
        String rupee = ledgerTable.getValueAt(r, 4).toString();
        String d= ledgerTable.getValueAt(r, 2).toString();
        ledgerBookIDtxt.setText(ledgerbookID);
        descriptionText.setText(des);
        //jDateChooser1.setDateFormat(dfc);
        ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).setText(d);
        rupees.setText(rupee);
    }//GEN-LAST:event_ledgerTableMouseClicked

    private void minimizedbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizedbtnMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizedbtnMouseClicked

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_closebtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Date1;
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel backbtn;
    private javax.swing.JTextField bankBookIDText;
    private javax.swing.JButton bankBookIdGenerate;
    private javax.swing.JTable bankBookTable;
    private javax.swing.JLabel bankbookID1;
    private javax.swing.JLabel bankbookID2;
    private javax.swing.JLabel bankbookID3;
    private javax.swing.JLabel bg;
    private javax.swing.JScrollPane cashBooktable;
    private javax.swing.JTextField chequeIDtxt;
    private javax.swing.JButton clearBankBook1;
    private javax.swing.JLabel closebtn;
    private javax.swing.JLabel date1;
    private javax.swing.JButton delete;
    private javax.swing.JLabel description;
    private javax.swing.JTextArea descriptionText;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton ledgerBookClear;
    private javax.swing.JTextField ledgerBookIDtxt;
    private javax.swing.JTable ledgerTable;
    private javax.swing.JLabel logoutbtn;
    private javax.swing.JLabel minimizedbtn;
    private javax.swing.JTextField rupees;
    private javax.swing.JLabel rupeeslbl;
    private javax.swing.JButton searchBUtton;
    private javax.swing.JLabel searchLedger;
    private javax.swing.JButton searchLedger1;
    private javax.swing.JSeparator spectator;
    private javax.swing.JLabel time1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
