/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gehan;


import dasun.OrderMainForm;
import static gehan.Login.curUserFname;
import janitha.Emp_Main;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kasun.Payroll_Main;
import roshane.vehicleMain;
import visura.main;

//import static ERP_System.Login.curUserFname;
/**
 *
 * @author gEhan
 */
public class Home extends javax.swing.JFrame {
    Connection con = null;          // Setting db connect to null
    PreparedStatement pst = null;                       // setting sql query statement to null
    ResultSet rs = null; 
    /**
     * Creates new form NewJFrame
     */
    public Home() {
        initComponents();
          try {
             new Thread(new Runnable() {

            @Override
            public void run() {
                Date d = new Date();
                SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

                String s2 = sd.format(d);
                date1.setText(s2);

            }
        }).start();
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    Date d = new Date();
                    String s = d.toString();
                    String ar[] = s.split(" ");
                    time1.setText(ar[3]);

                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
           // System.out.println(e);
        }
         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Employees = new javax.swing.JLabel();
        Accounts = new javax.swing.JLabel();
        Orders = new javax.swing.JLabel();
        Hello = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        notifylbl = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        shopnameLBL = new javax.swing.JLabel();
        addressLBL = new javax.swing.JLabel();
        Inventory = new javax.swing.JLabel();
        Sales = new javax.swing.JLabel();
        Payroll = new javax.swing.JLabel();
        Vehicles = new javax.swing.JLabel();
        menubutton = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        helloName = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setLocation(new java.awt.Point(175, 10));
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Elephant House Soft Drinks Distributors");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 70, 360, 26);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("To -");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 520, 30, 30);

        Employees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/EmpIcon.png"))); // NOI18N
        Employees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeesMouseClicked(evt);
            }
        });
        jPanel1.add(Employees);
        Employees.setBounds(670, 370, 100, 100);

        Accounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/AccountIcon.png"))); // NOI18N
        Accounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountsMouseClicked(evt);
            }
        });
        jPanel1.add(Accounts);
        Accounts.setBounds(730, 480, 100, 110);

        Orders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/orderIcon.png"))); // NOI18N
        Orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdersMouseClicked(evt);
            }
        });
        jPanel1.add(Orders);
        Orders.setBounds(590, 240, 120, 120);

        Hello.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        Hello.setForeground(new java.awt.Color(51, 51, 51));
        Hello.setText(" Hello,");
        jPanel1.add(Hello);
        Hello.setBounds(30, 330, 50, 30);
        Hello.getAccessibleContext().setAccessibleName("");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("You Have an Order -");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 490, 110, 30);

        notifylbl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        notifylbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(notifylbl);
        notifylbl.setBounds(200, 480, 160, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/minimizebtn.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14);
        jLabel14.setBounds(920, 10, 30, 30);

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/logoutbtn.png"))); // NOI18N
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
        });
        jPanel1.add(logoutbtn);
        logoutbtn.setBounds(950, 5, 25, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/closebtn.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16);
        jLabel16.setBounds(980, 10, 30, 30);

        shopnameLBL.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        shopnameLBL.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(shopnameLBL);
        shopnameLBL.setBounds(120, 520, 170, 30);

        addressLBL.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        addressLBL.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(addressLBL);
        addressLBL.setBounds(130, 570, 130, 20);

        Inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/InventoryIcon1.png"))); // NOI18N
        Inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryMouseClicked(evt);
            }
        });
        jPanel1.add(Inventory);
        Inventory.setBounds(440, 210, 90, 100);

        Sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/Sales.png"))); // NOI18N
        Sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalesMouseClicked(evt);
            }
        });
        jPanel1.add(Sales);
        Sales.setBounds(730, 220, 100, 100);

        Payroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/PayrollIcon.png"))); // NOI18N
        Payroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PayrollMouseClicked(evt);
            }
        });
        jPanel1.add(Payroll);
        Payroll.setBounds(550, 440, 100, 110);

        Vehicles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/VehicleIcon.png"))); // NOI18N
        Vehicles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VehiclesMouseClicked(evt);
            }
        });
        jPanel1.add(Vehicles);
        Vehicles.setBounds(450, 360, 100, 90);

        menubutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/menu-button.png"))); // NOI18N
        jPanel1.add(menubutton);
        menubutton.setBounds(10, 10, 20, 16);

        time1.setBackground(new java.awt.Color(255, 255, 255));
        time1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        time1.setForeground(new java.awt.Color(255, 255, 255));
        time1.setText("time");
        jPanel1.add(time1);
        time1.setBounds(720, 0, 70, 16);

        date1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("date");
        jPanel1.add(date1);
        date1.setBounds(710, 10, 80, 20);

        helloName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        helloName.setForeground(new java.awt.Color(51, 51, 51));
        helloName.setText("name");
        jPanel1.add(helloName);
        helloName.setBounds(80, 330, 100, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/HomeBackground.jpg"))); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, 0, 1024, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMouseClicked
        main mn = new main();
        mn.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_InventoryMouseClicked

    private void AccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountsMouseClicked
       Accounts accounts = new Accounts();
       accounts.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_AccountsMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // connect DB
        GetDBConnection1 dbc = new GetDBConnection1();
        helloName.setText(curUserFname);
        
          new Thread(new Runnable() {
            
            public void run() {
        String day = null;
        String shopname= null;
        String address= null;
        
         Date d = new Date();
         SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

         String s2 = sd.format(d);
        
        final String sql = " SELECT delivaryDate,shopName,shopAddress FROM order " ;
                try
            {    
                pst  = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
               
                    
                 
                while(rs.next())
                {
                   
                    Thread.sleep(3500);
                    day = rs.getString("delivaryDate");
                    shopname = rs.getString("shopName");
                    address = rs.getString("shopAddress");
                   
                   notifylbl.setText(String.valueOf(day));  
                   shopnameLBL.setText(String.valueOf(shopname));
                   addressLBL.setText(String.valueOf(address));
                }
                
               
                
            }
            catch(SQLException e)
            {
                  JOptionPane.showMessageDialog(null,"error : cannot execute sql  ");       
            }   catch (InterruptedException ex) {
                    Logger.getLogger(OrderMainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
        
        
      
        
    }//GEN-LAST:event_formWindowOpened

    private void EmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeesMouseClicked
        Emp_Main  emp = new Emp_Main();
        emp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EmployeesMouseClicked

    private void SalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesMouseClicked
       /* Sales sls = new Sales();
        sls.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_SalesMouseClicked

    private void OrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdersMouseClicked
       OrderMainForm ordr = new OrderMainForm();
        ordr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OrdersMouseClicked

    private void VehiclesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehiclesMouseClicked
      vehicleMain vm = new vehicleMain();
       vm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_VehiclesMouseClicked

    private void PayrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayrollMouseClicked
        // TODO add your handling code here:
        Payroll_Main pm = new Payroll_Main();
        pm.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_PayrollMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked

        Login l=new Login();
        l.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Accounts;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Employees;
    private javax.swing.JLabel Hello;
    private javax.swing.JLabel Inventory;
    private javax.swing.JLabel Orders;
    private javax.swing.JLabel Payroll;
    private javax.swing.JLabel Sales;
    private javax.swing.JLabel Vehicles;
    private javax.swing.JLabel addressLBL;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel helloName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoutbtn;
    private javax.swing.JLabel menubutton;
    private javax.swing.JLabel notifylbl;
    private javax.swing.JLabel shopnameLBL;
    private javax.swing.JLabel time1;
    // End of variables declaration//GEN-END:variables
}
