/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gehan;

import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author gEhan
 */
public class Login extends javax.swing.JFrame {

     ResultSet rs;
    PreparedStatement pst;  
    Statement st;  
    
    GetDBConnection1 dbc = new GetDBConnection1();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    try {
             new Thread(new Runnable() {

            @Override
            public void run() {
                Date d = new Date();
                SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

                String s2 = sd.format(d);
                date1.setText(s2);

            }
        }).start();
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    Date d = new Date();
                    String s = d.toString();
                    String ar[] = s.split(" ");
                    time1.setText(ar[3]);

                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
         
    }

        private static String username;
        private static String password;
        public static String curUserFname= null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        closebtn = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        date1 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 50));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setSize(new java.awt.Dimension(1024, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/menu-button.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 20, 20);

        closebtn.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        closebtn.setForeground(new java.awt.Color(204, 204, 204));
        closebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/closebtn.png"))); // NOI18N
        closebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closebtn.setPreferredSize(new java.awt.Dimension(30, 30));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        getContentPane().add(closebtn);
        closebtn.setBounds(980, 18, 25, 25);

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/logoutbtn.png"))); // NOI18N
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
        });
        getContentPane().add(logoutbtn);
        logoutbtn.setBounds(950, 10, 25, 40);

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/minimizebtn.png"))); // NOI18N
        getContentPane().add(Minimize);
        Minimize.setBounds(920, 15, 25, 30);

        txt_username.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        txt_username.setForeground(new java.awt.Color(0, 102, 0));
        txt_username.setMinimumSize(new java.awt.Dimension(190, 45));
        txt_username.setPreferredSize(new java.awt.Dimension(190, 45));
        txt_username.setSelectionColor(new java.awt.Color(0, 153, 0));
        txt_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usernameMouseClicked(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username);
        txt_username.setBounds(534, 326, 188, 45);

        loginBtn.setBackground(new java.awt.Color(0, 153, 0));
        loginBtn.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn);
        loginBtn.setBounds(630, 470, 80, 30);

        date1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("date");
        getContentPane().add(date1);
        date1.setBounds(720, 10, 70, 30);

        time1.setBackground(new java.awt.Color(255, 255, 255));
        time1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        time1.setForeground(new java.awt.Color(255, 255, 255));
        time1.setText("time");
        getContentPane().add(time1);
        time1.setBounds(720, 0, 70, 20);

        txt_password.setMinimumSize(new java.awt.Dimension(190, 45));
        txt_password.setPreferredSize(new java.awt.Dimension(190, 45));
        getContentPane().add(txt_password);
        txt_password.setBounds(534, 413, 188, 45);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/UserLogin.jpg"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1024, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usernameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         GetDBConnection1 dbc = new GetDBConnection1();
         
         
        
    }//GEN-LAST:event_formWindowOpened

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        // TODO add your handling code here:
        
            username = txt_username.getText();      // get login info from the user
            password = txt_password.getText();
            
            
            if(username.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter your Username");
            txt_username.requestFocusInWindow();               // move cursor to username field
            Login login = new Login ();
            login.setVisible(true);
            this.dispose();
        }
        
        else if(password.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter your Password");
            txt_password.requestFocusInWindow();
            Login login = new Login ();
            login.setVisible(true);
            this.dispose();
        }
        else
        {
            String sql = "select * from users where username=? and password=?";
               try
            {    
                pst  = dbc.con.prepareStatement(sql);

                pst.setString(1, username);
                
                pst.setString(2, password);
                

                ResultSet rs = pst.executeQuery();
                
                if(rs.next())
                {

                    curUserFname = rs.getString("fname");       // retreiving user's firstname from the database
                    String post = rs.getString("post");             // retreiving user's post
                    
                    
               /* -------perform login depending on the post------- */
                                                              
                    if(post.equals("Manager"))                      // if post is Manager go to Manager panel
                    {
                       
                        Home home = new Home();
                        home.setVisible(true);
                        this.dispose();
                       
                    }

                    else if(post.equals("Operator"))                    // if post is Operator go to Operator panel           
                    {
                        /*OperatorPanel G1 = new OperatorPanel();
                        G1.setVisible(true);
                        this.dispose();
                        */
                    }
                    
                    else if(post.equals("admin"))                    // if post is Administrator  go to Administrator panel           
                    {
                        Admin_Home adh = new Admin_Home();
                        adh.setVisible(true);
                        this.dispose();
                    }
                    
                }
                
                else
                {
                    JOptionPane.showMessageDialog(null,"Invalid Username or Password!");    // display error message
                }  
            }
            
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,"Error when executing sql startpage");
                System.out.println(e);

            }
            
                    
        }
    }//GEN-LAST:event_loginBtnMouseClicked

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_closebtnMouseClicked

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnActionPerformed

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked

    }//GEN-LAST:event_logoutbtnMouseClicked
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel closebtn;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel logoutbtn;
    private javax.swing.JLabel time1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
