/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dasun;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTextField;


public class Summary extends javax.swing.JFrame {
    Connection con = null;          // Setting db connect to null
    PreparedStatement pst = null;                       // setting sql query statement to null
    ResultSet rs = null; 
    
    public Summary() {
        initComponents();
        con = DBconnect.connect();
        
         try {
             new Thread(new Runnable() {

            @Override
            public void run() {
                Date d = new Date();
                SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

                String s2 = sd.format(d);
                date1.setText(s2);

            }
        }).start();
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    Date d = new Date();
                    String s = d.toString();
                    String ar[] = s.split(" ");
                    time1.setText(ar[3]);

                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        time1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        categoryCMB1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Bar200 = new javax.swing.JProgressBar();
        Bar250 = new javax.swing.JProgressBar();
        Bar350 = new javax.swing.JProgressBar();
        Bar400 = new javax.swing.JProgressBar();
        Bar500 = new javax.swing.JProgressBar();
        Bar15 = new javax.swing.JProgressBar();
        sumTXT = new javax.swing.JTextField();
        totalBTN = new javax.swing.JButton();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        totalBTN1 = new javax.swing.JButton();
        totalBTN2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1024, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(null);

        time1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        time1.setForeground(new java.awt.Color(255, 255, 255));
        time1.setText("time");
        jPanel1.add(time1);
        time1.setBounds(705, 0, 100, 16);

        date1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("date");
        jPanel1.add(date1);
        date1.setBounds(705, 14, 100, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backbtn.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(930, 10, 25, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/logoutbtn.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(960, 10, 25, 25);

        categoryCMB1.setBackground(new java.awt.Color(0, 153, 0));
        categoryCMB1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        categoryCMB1.setForeground(new java.awt.Color(255, 255, 255));
        categoryCMB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bottle Category", "Apple Soda", "Orange Barly", "Cream Soda", "EGB", "EGB Lite", "Lemonade", "Necto", "Orange Crush", "Soda", "Tonic", "Twistee Peach", "Twistee Apple", "Bitter Lemon", "Ginger Ale", "Wild Elephant" }));
        categoryCMB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryCMB1ActionPerformed(evt);
            }
        });
        jPanel1.add(categoryCMB1);
        categoryCMB1.setBounds(360, 100, 200, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("200ml");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 590, 50, 20);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("250ml");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 590, 50, 20);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("350ml");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(410, 590, 50, 20);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("400ml");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(560, 590, 50, 20);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("500ml PET");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(710, 590, 65, 20);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("1.5L PET");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(860, 590, 50, 20);

        Bar200.setBackground(new java.awt.Color(255, 255, 255));
        Bar200.setForeground(new java.awt.Color(255, 0, 51));
        Bar200.setMaximum(10);
        Bar200.setOrientation(1);
        jPanel1.add(Bar200);
        Bar200.setBounds(110, 210, 40, 350);

        Bar250.setBackground(new java.awt.Color(255, 255, 255));
        Bar250.setForeground(new java.awt.Color(255, 0, 51));
        Bar250.setMaximum(10);
        Bar250.setOrientation(1);
        jPanel1.add(Bar250);
        Bar250.setBounds(260, 210, 40, 350);

        Bar350.setBackground(new java.awt.Color(255, 255, 255));
        Bar350.setForeground(new java.awt.Color(255, 0, 51));
        Bar350.setMaximum(10);
        Bar350.setOrientation(1);
        jPanel1.add(Bar350);
        Bar350.setBounds(410, 210, 40, 350);

        Bar400.setBackground(new java.awt.Color(255, 255, 255));
        Bar400.setForeground(new java.awt.Color(255, 0, 51));
        Bar400.setMaximum(10);
        Bar400.setOrientation(1);
        jPanel1.add(Bar400);
        Bar400.setBounds(560, 210, 40, 350);

        Bar500.setBackground(new java.awt.Color(255, 255, 255));
        Bar500.setForeground(new java.awt.Color(255, 0, 51));
        Bar500.setMaximum(10);
        Bar500.setOrientation(1);
        jPanel1.add(Bar500);
        Bar500.setBounds(710, 210, 40, 350);

        Bar15.setBackground(new java.awt.Color(255, 255, 255));
        Bar15.setForeground(new java.awt.Color(255, 0, 51));
        Bar15.setMaximum(10);
        Bar15.setOrientation(1);
        jPanel1.add(Bar15);
        Bar15.setBounds(860, 210, 40, 350);
        jPanel1.add(sumTXT);
        sumTXT.setBounds(600, 100, 170, 30);

        totalBTN.setBackground(new java.awt.Color(0, 153, 0));
        totalBTN.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        totalBTN.setForeground(new java.awt.Color(255, 255, 255));
        totalBTN.setText("Total");
        totalBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBTNActionPerformed(evt);
            }
        });
        jPanel1.add(totalBTN);
        totalBTN.setBounds(810, 100, 110, 30);

        jDateChooser4.setDateFormatString("yyyy-MMM-d");
        jPanel1.add(jDateChooser4);
        jDateChooser4.setBounds(130, 100, 180, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Order's Report");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(70, 20, 330, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/closebtn.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(990, 10, 25, 25);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/minimizebtn.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(900, 10, 25, 25);

        totalBTN1.setBackground(new java.awt.Color(0, 153, 0));
        totalBTN1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        totalBTN1.setForeground(new java.awt.Color(255, 255, 255));
        totalBTN1.setText("Customer Report");
        totalBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBTN1ActionPerformed(evt);
            }
        });
        jPanel1.add(totalBTN1);
        totalBTN1.setBounds(470, 60, 190, 30);

        totalBTN2.setBackground(new java.awt.Color(0, 153, 0));
        totalBTN2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        totalBTN2.setForeground(new java.awt.Color(255, 255, 255));
        totalBTN2.setText("Order Report");
        totalBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBTN2ActionPerformed(evt);
            }
        });
        jPanel1.add(totalBTN2);
        totalBTN2.setBounds(210, 60, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backsup.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 720);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1024, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         OrderMainForm odrmForm = new OrderMainForm();
        odrmForm.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jLabel2MouseClicked

    private void categoryCMB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryCMB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryCMB1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//       int bar200;
//       int bar250;
//       int bar350;
//       int bar400;
//       int bar500;
//       int bar15;
//       
//      
//       String sql200 = "SELECT COUNT(amount) as count200 From `order` WHERE bottleSize='200ml'  ";
//       
//       String sql250 = "SELECT COUNT(amount) as count250 From `order` WHERE bottleSize='250ml'  ";
//       
//       String sql350 = "SELECT COUNT(amount) as count350 From `order` WHERE bottleSize='350ml'  ";
//       
//       String sql400 = "SELECT COUNT(amount) as count400 From `order` WHERE bottleSize='400ml' ";
//       
//       String sql500 = "SELECT COUNT(amount) as count500 From `order` WHERE bottleSize='500ml PET'  ";
//       
//       String sql15 = "SELECT COUNT(amount) as count15 From `order` WHERE bottleSize='1.5L PET'  ";
//       
//        /*200ml count*/
//       
//        try 
//        {
//            
//            pst=con.prepareStatement(sql200);
//            
//            rs = pst.executeQuery();
//            
//            if(rs.next()){
//                bar200 = rs.getInt("count200");
//                Bar200.setValue(bar200);
//            }
//            
//            
//        } catch (Exception e) {
//            System.out.println(e);
//        }
//         
//        /* 250ml count */
//         try {
//            pst=con.prepareStatement(sql250);
//            rs = pst.executeQuery();
//            
//            if(rs.next()){
//                bar250 = rs.getInt("count250");
//                Bar250.setValue(bar250);
//            }
//            
//            
//        } catch (Exception e) {
//            System.out.println(e);
//        }
//         
//         /* 350ml count*/
//         
//          try {
//            pst=con.prepareStatement(sql350);
//            rs = pst.executeQuery();
//            
//            if(rs.next()){
//                bar350 = rs.getInt("count350");
//                Bar350.setValue(bar350);
//            }
//            
//            
//        } catch (Exception e) {
//            System.out.println(e);
//        }
//          
//          /*400ml count*/
//          
//           try {
//            pst=con.prepareStatement(sql400);
//            rs = pst.executeQuery();
//            
//            if(rs.next()){
//                bar400 = rs.getInt("count400");
//                Bar400.setValue(bar400);
//            }
//            
//            
//        } catch (Exception e) {
//            System.out.println(e);
//        }
//           
//           /*500ml count*/
//           
//           try {
//            
//               pst=con.prepareStatement(sql500);
//               rs=pst.executeQuery();
//               
//               if(rs.next()){
//                   bar500 = rs.getInt("count500");
//                   Bar500.setValue(bar500);
//               }
//        } catch (Exception e) {
//        }
//           /*1.5l count*/
//           
//           try {
//            pst=con.prepareStatement(sql15);
//            rs=pst.executeQuery();
//            
//            if(rs.next()){
//                bar15 = rs.getInt("count15");
//                Bar15.setValue(bar15);
//            }
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_formWindowOpened

    private void totalBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBTNActionPerformed
        String category = null;
        category = categoryCMB1.getSelectedItem().toString();
        String  day=((JTextField)jDateChooser4.getDateEditor().getUiComponent()).getText();
    //    String d1  = ((JTextField)jDateChooser4.getDateEditor().getUiComponent()).getText();

      
        try {
            String sql = "SELECT sum(amount) from `order` where bottleCategory='"+category+"' and delivaryDate='"+day+"'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            if(rs.next()){
                String sum=rs.getString("sum(amount)");
                sumTXT.setText(sum);
            }
                    
        } catch (Exception e) {
        }
        
       /*---------------BAR code----------------*/ 
        
       int bar200;
       int bar250;
       int bar350;
       int bar400;
       int bar500;
       int bar15;
       
      
       String sql200 = "SELECT COUNT(amount) as count200 From `order` WHERE bottleSize='200ml' and bottleCategory='"+category+"' and delivaryDate='"+day+"' ";
       
       String sql250 = "SELECT COUNT(amount) as count250 From `order` WHERE bottleSize='250ml' and bottleCategory='"+category+"' and delivaryDate='"+day+"' ";
       
       String sql350 = "SELECT COUNT(amount) as count350 From `order` WHERE bottleSize='350ml' and bottleCategory='"+category+"' and delivaryDate='"+day+"'";
       
       String sql400 = "SELECT COUNT(amount) as count400 From `order` WHERE bottleSize='400ml'and bottleCategory='"+category+"' and delivaryDate='"+day+"'";
       
       String sql500 = "SELECT COUNT(amount) as count500 From `order` WHERE bottleSize='500ml PET' and bottleCategory='"+category+"' and delivaryDate='"+day+"' ";
       
       String sql15 = "SELECT COUNT(amount) as count15 From `order` WHERE bottleSize='1.5L PET' and bottleCategory='"+category+"' and delivaryDate='"+day+"' ";
       
        /*200ml count*/
       
        try 
        {
            
            pst=con.prepareStatement(sql200);
            
            rs = pst.executeQuery();
            
            if(rs.next()){
                bar200 = rs.getInt("count200");
                Bar200.setValue(bar200);
            }
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
         
        /* 250ml count */
         try {
            pst=con.prepareStatement(sql250);
            rs = pst.executeQuery();
            
            if(rs.next()){
                bar250 = rs.getInt("count250");
                Bar250.setValue(bar250);
            }
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
         
         /* 350ml count*/
         
          try {
            pst=con.prepareStatement(sql350);
            rs = pst.executeQuery();
            
            if(rs.next()){
                bar350 = rs.getInt("count350");
                Bar350.setValue(bar350);
            }
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
          
          /*400ml count*/
          
           try {
            pst=con.prepareStatement(sql400);
            rs = pst.executeQuery();
            
            if(rs.next()){
                bar400 = rs.getInt("count400");
                Bar400.setValue(bar400);
            }
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
           
           /*500ml count*/
           
           try {
            
               pst=con.prepareStatement(sql500);
               rs=pst.executeQuery();
               
               if(rs.next()){
                   bar500 = rs.getInt("count500");
                   Bar500.setValue(bar500);
               }
        } catch (Exception e) {
        }
           /*1.5l count*/
           
           try {
            pst=con.prepareStatement(sql15);
            rs=pst.executeQuery();
            
            if(rs.next()){
                bar15 = rs.getInt("count15");
                Bar15.setValue(bar15);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_totalBTNActionPerformed

    private void totalBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBTN1ActionPerformed
      ReportView1 dy =new ReportView1("C:\\Users\\User\\Desktop\\Final ERP Sysytm\\dasun1.jasper");
        dy.setVisible(true);
                            
    }//GEN-LAST:event_totalBTN1ActionPerformed

    private void totalBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBTN2ActionPerformed
       ReportView1 dx =new ReportView1("C:\\Users\\User\\Desktop\\Final ERP Sysytm\\dasun3.jasper");
        dx.setVisible(true);
    }//GEN-LAST:event_totalBTN2ActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Summary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Summary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Bar15;
    private javax.swing.JProgressBar Bar200;
    private javax.swing.JProgressBar Bar250;
    private javax.swing.JProgressBar Bar350;
    private javax.swing.JProgressBar Bar400;
    private javax.swing.JProgressBar Bar500;
    private javax.swing.JComboBox<String> categoryCMB1;
    private javax.swing.JLabel date1;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField sumTXT;
    private javax.swing.JLabel time1;
    private javax.swing.JButton totalBTN;
    private javax.swing.JButton totalBTN1;
    private javax.swing.JButton totalBTN2;
    // End of variables declaration//GEN-END:variables
}
