/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roshane;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public final class notification extends javax.swing.JFrame {
   Connection con = null;
   PreparedStatement pst;
   ResultSet rs =null;
    /**
     * Creates new form notification
     */
    public notification() {
        this.pst = null;
        initComponents();
        
         try {
             new Thread(new Runnable() {

            @Override
            public void run() {
                Date d = new Date();
                SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

                String s2 = sd.format(d);
                date1.setText(s2);

            }
        }).start();
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    Date d = new Date();
                    String s = d.toString();
                    String ar[] = s.split(" ");
                    time1.setText(ar[3]);

                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        con = DBconnect.connect();
        //this.setLocationRelativeTo(null);
        tableLoad();
        
         try {
             new Thread(new Runnable() {

            @Override
            public void run() {
                Date d = new Date();
                SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

                String s2 = sd.format(d);
                date1.setText(s2);

            }
        }).start();
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    Date d = new Date();
                    String s = d.toString();
                    String ar[] = s.split(" ");
                    time1.setText(ar[3]);

                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
         
    }
    public void tableLoad()
    {
        try {
             String sql = "SELECT * FROM `transport details`";  
            pst=con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
        }
    }
    
    String did;
    String vno;
    String rno;
    String cont;
    String timein;
    String timeout;
    String des;
    String model;
    String capacity;
    String veType;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dtxt = new javax.swing.JTextField();
        vtxt = new javax.swing.JTextField();
        rtxt = new javax.swing.JTextField();
        contxt = new javax.swing.JTextField();
        titxt = new javax.swing.JTextField();
        totxt = new javax.swing.JTextField();
        UPDATE = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        destxt = new javax.swing.JTextField();
        ADD = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        searchTXT = new javax.swing.JTextField();
        serchBTN = new javax.swing.JButton();
        time1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        vtTXT = new javax.swing.JComboBox<>();
        CTXT = new javax.swing.JTextField();
        MTXT = new javax.swing.JTextField();
        cmb2 = new javax.swing.JComboBox<>();
        backbtn = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setPreferredSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Driver Id");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 130, 60, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vehicle No");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 170, 100, 30);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(37, 180, 0, 0);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Reg No");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 220, 100, 30);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(105, 241, 0, 0);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 250, 100, 30);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Time in");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(430, 200, 50, 30);

        dtxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jPanel1.add(dtxt);
        dtxt.setBounds(110, 130, 270, 30);

        vtxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        vtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vtxtActionPerformed(evt);
            }
        });
        jPanel1.add(vtxt);
        vtxt.setBounds(110, 170, 270, 30);

        rtxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        rtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtxtActionPerformed(evt);
            }
        });
        jPanel1.add(rtxt);
        rtxt.setBounds(110, 210, 270, 30);

        contxt.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jPanel1.add(contxt);
        contxt.setBounds(110, 250, 270, 30);
        jPanel1.add(titxt);
        titxt.setBounds(510, 200, 270, 30);

        totxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totxtActionPerformed(evt);
            }
        });
        jPanel1.add(totxt);
        totxt.setBounds(510, 240, 270, 30);

        UPDATE.setBackground(new java.awt.Color(0, 153, 0));
        UPDATE.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        UPDATE.setForeground(new java.awt.Color(255, 255, 255));
        UPDATE.setText("Update");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        jPanel1.add(UPDATE);
        UPDATE.setBounds(460, 470, 120, 30);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Time out");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(430, 240, 70, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Destination");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(430, 290, 90, 20);

        destxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destxtActionPerformed(evt);
            }
        });
        jPanel1.add(destxt);
        destxt.setBounds(510, 280, 270, 30);

        ADD.setBackground(new java.awt.Color(0, 153, 0));
        ADD.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ADD.setForeground(new java.awt.Color(255, 255, 255));
        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        jPanel1.add(ADD);
        ADD.setBounds(170, 470, 120, 30);

        DELETE.setBackground(new java.awt.Color(0, 153, 0));
        DELETE.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        DELETE.setForeground(new java.awt.Color(255, 255, 255));
        DELETE.setText("Delete");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel1.add(DELETE);
        DELETE.setBounds(750, 470, 120, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Transport  Details");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 20, 280, 30);
        jPanel1.add(searchTXT);
        searchTXT.setBounds(650, 120, 140, 30);

        serchBTN.setBackground(new java.awt.Color(0, 153, 0));
        serchBTN.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        serchBTN.setForeground(new java.awt.Color(255, 255, 255));
        serchBTN.setText("GO");
        serchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serchBTNActionPerformed(evt);
            }
        });
        jPanel1.add(serchBTN);
        serchBTN.setBounds(700, 160, 90, 25);

        time1.setForeground(new java.awt.Color(255, 255, 255));
        time1.setText("Time");
        jPanel1.add(time1);
        time1.setBounds(700, 0, 120, 20);

        date1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("Date");
        date1.setRequestFocusEnabled(false);
        jPanel1.add(date1);
        date1.setBounds(700, 15, 90, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(100, 540, 810, 110);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Model");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 300, 100, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Capacity");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 340, 100, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Vehicle Type");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 380, 100, 30);

        vtTXT.setBackground(new java.awt.Color(0, 153, 0));
        vtTXT.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        vtTXT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Van", "Lorry" }));
        jPanel1.add(vtTXT);
        vtTXT.setBounds(110, 380, 150, 30);

        CTXT.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        CTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTXTActionPerformed(evt);
            }
        });
        jPanel1.add(CTXT);
        CTXT.setBounds(110, 330, 270, 30);

        MTXT.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jPanel1.add(MTXT);
        MTXT.setBounds(110, 290, 270, 30);

        cmb2.setBackground(new java.awt.Color(51, 204, 0));
        cmb2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cmb2.setForeground(new java.awt.Color(255, 255, 255));
        cmb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Driver Id", "Vehicle No" }));
        jPanel1.add(cmb2);
        cmb2.setBounds(510, 120, 120, 30);

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backbtn.png"))); // NOI18N
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        jPanel1.add(backbtn);
        backbtn.setBounds(920, 10, 30, 30);

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/logoutbtn.png"))); // NOI18N
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
        });
        jPanel1.add(logoutbtn);
        logoutbtn.setBounds(950, 10, 30, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/minimizebtn.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(890, 10, 30, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/closebtn.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16);
        jLabel16.setBounds(980, 10, 30, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backsup.jpg"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 1024, 720);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 720));

        setSize(new java.awt.Dimension(1040, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
   int x = JOptionPane.showConfirmDialog(null, "Do You Really Want to Update");
        if(x==0){
        String did=dtxt.getText();
        String vno=vtxt.getText();
        String rno=rtxt.getText();
        String cont=contxt.getText();
        String timein=titxt.getText();
        String timeout=totxt.getText();
        String des=destxt.getText(); 
        String model = MTXT.getText();
        String capacity = CTXT.getText();
        String veType = vtTXT.getSelectedItem().toString();
        String sql3 ="UPDATE `transport details` SET did='"+did+"',vno = '"+vno+"',regno='"+rno+"',contact='"+cont+"',timein='"+timein+"' , timeout='"+timeout+"',destination='"+des+"',model='"+model+"',capacity='"+capacity+"',vtype='"+veType+"'  WHERE vno = '"+vno+"'";
      try{
      
      pst=con.prepareStatement(sql3);
      pst.execute();
      
      tableLoad();
      
      }
      catch (Exception e){
      }
        }
            
    }//GEN-LAST:event_UPDATEActionPerformed

    private void vtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vtxtActionPerformed

    private void rtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtxtActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
      String did=dtxt.getText();
      String vno=vtxt.getText();
      String rno=rtxt.getText();
      String cont=contxt.getText();
      String timein=titxt.getText();
      String timeout=totxt.getText();
      String  des=destxt.getText(); 
      String model = MTXT.getText();
      String capacity = CTXT.getText();
      String veType = vtTXT.getSelectedItem().toString();
     
     
     
     
     try {
          String sql1="INSERT INTO `transport details`(did,vno,regno,contact,timein,timeout,destination,model,capacity,vtype)  values('"+did+"','"+vno+"','"+rno+"','"+cont+"','"+timein+"','"+timeout+"','"+des+"','"+model+"','"+capacity+"','"+veType+"')";

          
          pst=con.prepareStatement(sql1);
          pst.execute();
           tableLoad();
      }
      catch(Exception e){
          System.out.println(e);
      }
     
// TODO add your handling code here:
    }//GEN-LAST:event_ADDActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
    int y=JOptionPane.showConfirmDialog(null,"Do you really want to Delete");
        if (y==0){
         vno=vtxt.getText();
        String sql16="DELETE from `transport details` where vno='"+vno+"'";
        
         
        
         try{
      pst=con.prepareStatement(sql16);
      pst.execute();     
      tableLoad();
            }
      catch (Exception e){
          System.out.println(e);
      }
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_DELETEActionPerformed

    private void totxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totxtActionPerformed

    private void destxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destxtActionPerformed

    private void serchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serchBTNActionPerformed
         String shopname = searchTXT.getText();
       
        
        
        String sql = "SELECT did,vno,regno,contact,timein,timeout,destination,model,capacity,vtype from `transport details` where did LIKE '%"+shopname+"%'";
        try {
              pst =con.prepareStatement(sql);
        rs = pst.executeQuery();
      
         jTable1.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_serchBTNActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      int row  = jTable1.getSelectedRow();
          
        String did = jTable1.getValueAt(row, 0).toString();
        String vno = jTable1.getValueAt(row, 1).toString();
        String rno = jTable1.getValueAt(row, 2).toString();
        String cont = jTable1.getValueAt(row, 3).toString();
        String timein = jTable1.getValueAt(row, 4).toString();
        String timeout = jTable1.getValueAt(row, 5).toString();
        String des = jTable1.getValueAt(row, 6).toString();
        String model = jTable1.getValueAt(row, 7).toString();
        String capacity = jTable1.getValueAt(row, 8).toString();
        String veType = jTable1.getValueAt(row, 9).toString();
         
         
         
        dtxt.setText(did);
        vtxt.setText(vno);
        rtxt.setText(rno);
        contxt.setText(cont);
        titxt.setText(timein);
        totxt.setText(timeout);
        destxt.setText(des);
        MTXT.setText(model);
        CTXT.setText(capacity);
        vtTXT.setSelectedItem(veType);
        
        
   
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void CTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CTXTActionPerformed

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        vehicleMain mn = new vehicleMain();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnMouseClicked

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked
       
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
         this.dispose();
        
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new notification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JTextField CTXT;
    private javax.swing.JButton DELETE;
    private javax.swing.JTextField MTXT;
    private javax.swing.JButton UPDATE;
    private javax.swing.JLabel backbtn;
    private javax.swing.JComboBox<String> cmb2;
    private javax.swing.JTextField contxt;
    private javax.swing.JLabel date1;
    private javax.swing.JTextField destxt;
    private javax.swing.JTextField dtxt;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logoutbtn;
    private javax.swing.JTextField rtxt;
    private javax.swing.JTextField searchTXT;
    private javax.swing.JButton serchBTN;
    private javax.swing.JLabel time1;
    private javax.swing.JTextField titxt;
    private javax.swing.JTextField totxt;
    private javax.swing.JComboBox<String> vtTXT;
    private javax.swing.JTextField vtxt;
    // End of variables declaration//GEN-END:variables
}
