package roshane;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Roshen Aponsu
 */
public class Vehiclecharge extends javax.swing.JFrame {
    
   Connection con = null;
   PreparedStatement pst;
   ResultSet rs =null;
    

    
    public Vehiclecharge() {
       this.pst = null;
        initComponents();
          try {
             new Thread(new Runnable() {

            @Override
            public void run() {
                Date d = new Date();
                SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

                String s2 = sd.format(d);
                date1.setText(s2);

            }
        }).start();
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    Date d = new Date();
                    String s = d.toString();
                    String ar[] = s.split(" ");
                    time1.setText(ar[3]);

                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }).start();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        con = DBconnect.connect();
        
        tableload();
    }
    
    
    public void tableload()
    {
       try{
        String sql = "SELECT vno,vtype,ser,fuelc,fuelt,total FROM `vehicle main`";
        pst=con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
          
       }catch (Exception e) {
       }
        
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backbtn = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JLabel();
        cmb3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        go = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        RETXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmb2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        sc = new javax.swing.JTextField();
        vn1 = new javax.swing.JTextField();
        fc = new javax.swing.JTextField();
        time1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        VTXT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backbtn.png"))); // NOI18N
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        jPanel1.add(backbtn);
        backbtn.setBounds(930, 10, 25, 25);

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/logoutbtn.png"))); // NOI18N
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
        });
        jPanel1.add(logoutbtn);
        logoutbtn.setBounds(960, 10, 25, 25);

        cmb3.setBackground(new java.awt.Color(51, 204, 0));
        cmb3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cmb3.setForeground(new java.awt.Color(255, 255, 255));
        cmb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petrol", "Diesel" }));
        jPanel1.add(cmb3);
        cmb3.setBounds(629, 191, 150, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehicle Type");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(39, 147, 63, 16);

        go.setBackground(new java.awt.Color(51, 204, 0));
        go.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        go.setForeground(new java.awt.Color(255, 255, 255));
        go.setText("Search");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        jPanel1.add(go);
        go.setBounds(800, 90, 83, 30);

        jButton3.setBackground(new java.awt.Color(51, 204, 0));
        jButton3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(470, 420, 92, 31);

        jButton4.setBackground(new java.awt.Color(51, 204, 0));
        jButton4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(730, 420, 94, 31);
        jPanel1.add(RETXT);
        RETXT.setBounds(132, 326, 152, 29);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Vehicle No");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(539, 95, 53, 16);

        cmb2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cmb2.setForeground(new java.awt.Color(255, 255, 255));
        cmb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Van ", "Lorry" }));
        jPanel1.add(cmb2);
        cmb2.setBounds(130, 140, 150, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(101, 520, 800, 110);

        sa.setBackground(new java.awt.Color(51, 204, 0));
        sa.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        sa.setForeground(new java.awt.Color(255, 255, 255));
        sa.setText("Total Cost");
        sa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saActionPerformed(evt);
            }
        });
        jPanel1.add(sa);
        sa.setBounds(340, 320, 92, 31);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Service charge");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(26, 208, 72, 16);
        jPanel1.add(sc);
        sc.setBounds(132, 202, 152, 29);

        vn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vn1ActionPerformed(evt);
            }
        });
        jPanel1.add(vn1);
        vn1.setBounds(629, 89, 146, 28);
        jPanel1.add(fc);
        fc.setBounds(132, 263, 152, 32);

        time1.setBackground(new java.awt.Color(255, 255, 255));
        time1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        time1.setForeground(new java.awt.Color(255, 255, 255));
        time1.setText("time");
        jPanel1.add(time1);
        time1.setBounds(710, 0, 70, 20);

        date1.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 255, 255));
        date1.setText("date");
        jPanel1.add(date1);
        date1.setBounds(710, 15, 60, 20);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vehicle No");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(52, 82, 53, 16);

        VTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VTXTActionPerformed(evt);
            }
        });
        jPanel1.add(VTXT);
        VTXT.setBounds(132, 76, 152, 28);

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 420, 95, 31);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fuel Type");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(544, 194, 48, 16);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vehicle Maintain Expences");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 20, 400, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fuel charge");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(45, 271, 57, 16);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/closebtn.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(990, 10, 25, 25);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/minimizebtn.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(900, 10, 25, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BackGroundImages/backsup.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 1024, 720);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VTXTActionPerformed

    private void vn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vn1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          int x = JOptionPane.showConfirmDialog(null, "Do You Really Want to Update");
        if(x==0){
        
        String vno = VTXT.getText();
        String veType = cmb2.getSelectedItem().toString();
        String Scharge = sc.getText();
        String Fcharge= fc.getText();
        String FType=cmb3.getSelectedItem().toString();
        String Sum  =RETXT.getText();
        
        String sq13 = "UPDATE `vehicle main` SET vno='"+vno+"',vtype='"+veType+"',ser='"+Scharge+"',fuelc='"+Fcharge+"',fuelt='"+FType+"',total='"+Sum+"' where vno='"+vno+"'";

        try{
                     pst=con.prepareStatement(sq13); 
           pst.execute();
           tableload();
           
           }
            catch (Exception e){
                
            }
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
              int x=JOptionPane.showConfirmDialog(null,"Do you really want to Delete");
        if (x==0){
        String vno=VTXT.getText();
        String sql16="DELETE  from `vehicle main` where vno='"+vno+"'";
        
         
        
         try{
      pst=con.prepareStatement(sql16);
      pst.execute();     
      tableload();
            }
      catch (Exception e){
          System.out.println(e);
      }
        
        }  
    
            else{
    
}
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String vno = VTXT.getText();
        String veType = cmb2.getSelectedItem().toString();
        String Scharge = sc.getText();
        String Fcharge= fc.getText();
        String FType=cmb3.getSelectedItem().toString();
        String Sum  =RETXT.getText();
        
      
        
        String q12 = "INSERT INTO `vehicle main`(vno,vtype,ser,fuelc,fuelt,total) values('"+vno+"','"+veType+"','"+Scharge+"','"+Fcharge+"','"+FType+"','"+Sum+"')";
              try{
                pst = con.prepareStatement(q12);
                pst.execute();
                
                tableload();
                    
                
              }
            catch (Exception e) {
               
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r = jTable1.getSelectedRow();
        
        String vno = jTable1.getValueAt(r, 0).toString();
        String vType = jTable1.getValueAt(r, 1).toString();
        String Scharge = jTable1.getValueAt(r, 2).toString();
        String Fcharge = jTable1.getValueAt(r, 3).toString();
        String FType = jTable1.getValueAt(r, 4).toString();
        String Sum   = jTable1.getValueAt(r, 5).toString();
        
        VTXT.setText(vno);
        cmb2.setSelectedItem(vType);
        sc.setText(Scharge);
        fc.setText(Fcharge);
        cmb3.setSelectedItem(FType);
        RETXT.setText(Sum);
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void saActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saActionPerformed
         double v1,v2;
         v1=Double.valueOf(sc.getText());
         v2=Double.valueOf(fc.getText());
         double s;
         s=v1+v2;
         RETXT.setText(""+s);
         

    }//GEN-LAST:event_saActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
         String vehicleno = vn1.getText();
         try{
         
         String sql= "SELECT vno,vtype,ser,fuelc,fuelt,total from `vehicle main` where vno LIKE '"+vehicleno+"%'";
         pst = con.prepareStatement(sql);
         rs = pst.executeQuery();
         
         jTable1.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
         
         } catch(Exception e){ 
             
         }   
         
    }//GEN-LAST:event_goActionPerformed

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        vehicleMain mn = new vehicleMain();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnMouseClicked

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked
        
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehiclecharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehiclecharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehiclecharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehiclecharge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehiclecharge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RETXT;
    private javax.swing.JTextField VTXT;
    private javax.swing.JLabel backbtn;
    private javax.swing.JComboBox<String> cmb2;
    private javax.swing.JComboBox<String> cmb3;
    private javax.swing.JLabel date1;
    private javax.swing.JTextField fc;
    private javax.swing.JButton go;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logoutbtn;
    private javax.swing.JButton sa;
    private javax.swing.JTextField sc;
    private javax.swing.JLabel time1;
    private javax.swing.JTextField vn1;
    // End of variables declaration//GEN-END:variables

}

